var _pre_approval_plan_client_i_t_test_8php =
[
    [ "MercadoPago\\Tests\\Client\\Integration\\PreApprovalPlan\\PreApprovalPlanClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_plan_1_1_pre_approval_plan_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_plan_1_1_pre_approval_plan_client_i_t_test" ]
];