var dir_97f27a8d3efc40e8fefbbd7dfe5560e8 =
[
    [ "beneficios_premium.php", "beneficios__premium_8php.html", null ],
    [ "carrousel.php", "carrousel_8php.html", null ],
    [ "chat.php", "dashboard_2chat_8php.html", "dashboard_2chat_8php" ],
    [ "conexion.php", "dashboard_2conexion_8php.html", "dashboard_2conexion_8php" ],
    [ "contactanos.php", "contactanos_8php.html", null ],
    [ "credenciales.php", "credenciales_8php.html", "credenciales_8php" ],
    [ "enviar_factura.php", "enviar__factura_8php.html", "enviar__factura_8php" ],
    [ "footer.php", "footer_8php.html", null ],
    [ "header.php", "header_8php.html", "header_8php" ],
    [ "index.php", "dashboard_2index_8php.html", null ],
    [ "login.php", "dashboard_2login_8php.html", null ],
    [ "logout.php", "logout_8php.html", null ],
    [ "mail.php", "mail_8php.html", "mail_8php" ],
    [ "manual.php", "manual_8php.html", null ],
    [ "mercadopago.php", "mercadopago_8php.html", null ],
    [ "Nicole.php", "_nicole_8php.html", null ],
    [ "other.php", "other_8php.html", null ],
    [ "pago_exitoso.php", "pago__exitoso_8php.html", "pago__exitoso_8php" ],
    [ "pago_fallido.php", "pago__fallido_8php.html", null ],
    [ "pago_pendiente.php", "pago__pendiente_8php.html", null ],
    [ "preferencias.php", "preferencias_8php.html", "preferencias_8php" ],
    [ "presentacioncuadro.php", "presentacioncuadro_8php.html", null ],
    [ "privacidad.php", "privacidad_8php.html", null ],
    [ "procesar_login.php", "procesar__login_8php.html", "procesar__login_8php" ],
    [ "procesar_registro.php", "procesar__registro_8php.html", "procesar__registro_8php" ],
    [ "que-hacemos.php", "que-hacemos_8php.html", null ],
    [ "quienes-somos.php", "quienes-somos_8php.html", null ],
    [ "recuperar.php", "dashboard_2recuperar_8php.html", null ],
    [ "registro.php", "registro_8php.html", "registro_8php" ],
    [ "scripts.php", "scripts_8php.html", null ],
    [ "stylesheet.php", "stylesheet_8php.html", null ],
    [ "terminos.php", "terminos_8php.html", null ],
    [ "test_webhook.php", "test__webhook_8php.html", "test__webhook_8php" ],
    [ "verificar.php", "dashboard_2verificar_8php.html", "dashboard_2verificar_8php" ],
    [ "webhook.php", "webhook_8php.html", "webhook_8php" ]
];