var dir_8a6b2eb5560f782bc4768121fcb79af9 =
[
    [ "Address.php", "_user_2_address_8php.html", "_user_2_address_8php" ],
    [ "AlternativePhone.php", "_alternative_phone_8php.html", "_alternative_phone_8php" ],
    [ "BillData.php", "_bill_data_8php.html", "_bill_data_8php" ],
    [ "BuyerReputation.php", "_buyer_reputation_8php.html", "_buyer_reputation_8php" ],
    [ "BuyerReputationCancelled.php", "_buyer_reputation_cancelled_8php.html", "_buyer_reputation_cancelled_8php" ],
    [ "BuyerReputationNotYetRated.php", "_buyer_reputation_not_yet_rated_8php.html", "_buyer_reputation_not_yet_rated_8php" ],
    [ "BuyerReputationTransactions.php", "_buyer_reputation_transactions_8php.html", "_buyer_reputation_transactions_8php" ],
    [ "BuyerReputationUnrated.php", "_buyer_reputation_unrated_8php.html", "_buyer_reputation_unrated_8php" ],
    [ "Cancellations.php", "_cancellations_8php.html", "_cancellations_8php" ],
    [ "Claims.php", "_claims_8php.html", "_claims_8php" ],
    [ "Company.php", "_company_8php.html", "_company_8php" ],
    [ "Context.php", "_context_8php.html", "_context_8php" ],
    [ "Credit.php", "_credit_8php.html", "_credit_8php" ],
    [ "DelayedHandlingTime.php", "_delayed_handling_time_8php.html", "_delayed_handling_time_8php" ],
    [ "Metrics.php", "_metrics_8php.html", "_metrics_8php" ],
    [ "Phone.php", "_user_2_phone_8php.html", "_user_2_phone_8php" ],
    [ "Ratings.php", "_ratings_8php.html", "_ratings_8php" ],
    [ "Sales.php", "_sales_8php.html", "_sales_8php" ],
    [ "SellerReputation.php", "_seller_reputation_8php.html", "_seller_reputation_8php" ],
    [ "Status.php", "_status_8php.html", "_status_8php" ],
    [ "StatusBilling.php", "_status_billing_8php.html", "_status_billing_8php" ],
    [ "StatusBuyImmediatePayment.php", "_status_buy_immediate_payment_8php.html", "_status_buy_immediate_payment_8php" ],
    [ "StatusList.php", "_status_list_8php.html", "_status_list_8php" ],
    [ "StatusShoppingCart.php", "_status_shopping_cart_8php.html", "_status_shopping_cart_8php" ],
    [ "Transactions.php", "_user_2_transactions_8php.html", "_user_2_transactions_8php" ]
];