var hierarchy =
[
    [ "MercadoPago\\Resources\\Payment\\AdditionalInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info.html", null ],
    [ "MercadoPago\\Resources\\Payment\\AdditionalInfoPayer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info_payer.html", null ],
    [ "MercadoPago\\Resources\\Common\\Address", "class_mercado_pago_1_1_resources_1_1_common_1_1_address.html", [
      [ "MercadoPago\\Resources\\Payment\\ReceiverAddress", "class_mercado_pago_1_1_resources_1_1_payment_1_1_receiver_address.html", null ],
      [ "MercadoPago\\Resources\\Preference\\ReceiverAddress", "class_mercado_pago_1_1_resources_1_1_preference_1_1_receiver_address.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\User\\Address", "class_mercado_pago_1_1_resources_1_1_user_1_1_address.html", null ],
    [ "MercadoPago\\Resources\\User\\AlternativePhone", "class_mercado_pago_1_1_resources_1_1_user_1_1_alternative_phone.html", null ],
    [ "MercadoPago\\Resources\\Payment\\ApplicationData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_application_data.html", null ],
    [ "MercadoPago\\Resources\\Order\\Attempt", "class_mercado_pago_1_1_resources_1_1_order_1_1_attempt.html", null ],
    [ "Attribute", "class_attribute.html", null ],
    [ "MercadoPago\\Resources\\Order\\AutomaticPayments", "class_mercado_pago_1_1_resources_1_1_order_1_1_automatic_payments.html", null ],
    [ "MercadoPago\\Resources\\PreApproval\\AutoRecurring", "class_mercado_pago_1_1_resources_1_1_pre_approval_1_1_auto_recurring.html", null ],
    [ "MercadoPago\\Resources\\PreApprovalPlan\\AutoRecurring", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_auto_recurring.html", null ],
    [ "MercadoPago\\Resources\\Payment\\BankInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info.html", null ],
    [ "MercadoPago\\Resources\\Payment\\BankInfoCollector", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_collector.html", null ],
    [ "MercadoPago\\Resources\\Payment\\BankInfoPayer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_payer.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Barcode", "class_mercado_pago_1_1_resources_1_1_payment_1_1_barcode.html", null ],
    [ "MercadoPago\\Resources\\User\\BillData", "class_mercado_pago_1_1_resources_1_1_user_1_1_bill_data.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\Bin", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_bin.html", null ],
    [ "MercadoPago\\Resources\\User\\BuyerReputation", "class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation.html", null ],
    [ "MercadoPago\\Resources\\User\\BuyerReputationCancelled", "class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_cancelled.html", null ],
    [ "MercadoPago\\Resources\\User\\BuyerReputationNotYetRated", "class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_not_yet_rated.html", null ],
    [ "MercadoPago\\Resources\\User\\BuyerReputationTransactions", "class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_transactions.html", null ],
    [ "MercadoPago\\Resources\\User\\BuyerReputationUnrated", "class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_unrated.html", null ],
    [ "MercadoPago\\Resources\\User\\Cancellations", "class_mercado_pago_1_1_resources_1_1_user_1_1_cancellations.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Card", "class_mercado_pago_1_1_resources_1_1_payment_1_1_card.html", null ],
    [ "MercadoPago\\Resources\\Customer\\Cardholder", "class_mercado_pago_1_1_resources_1_1_customer_1_1_cardholder.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Cardholder", "class_mercado_pago_1_1_resources_1_1_payment_1_1_cardholder.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\CardNumber", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_card_number.html", null ],
    [ "MercadoPago\\Resources\\Preference\\CategoryDescriptor", "class_mercado_pago_1_1_resources_1_1_preference_1_1_category_descriptor.html", null ],
    [ "MercadoPago\\Resources\\Common\\City", "class_mercado_pago_1_1_resources_1_1_common_1_1_city.html", null ],
    [ "MercadoPago\\Resources\\User\\Claims", "class_mercado_pago_1_1_resources_1_1_user_1_1_claims.html", null ],
    [ "Composer\\Autoload\\ClassLoader", "class_composer_1_1_autoload_1_1_class_loader.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\Collector", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_collector.html", null ],
    [ "MercadoPago\\Resources\\User\\Company", "class_mercado_pago_1_1_resources_1_1_user_1_1_company.html", null ],
    [ "ComposerAutoloaderInit2185d2f99bcd56787481d9357a5972d3", "class_composer_autoloader_init2185d2f99bcd56787481d9357a5972d3.html", null ],
    [ "Composer\\Autoload\\ComposerStaticInit2185d2f99bcd56787481d9357a5972d3", "class_composer_1_1_autoload_1_1_composer_static_init2185d2f99bcd56787481d9357a5972d3.html", null ],
    [ "MercadoPago\\Resources\\Order\\Config", "class_mercado_pago_1_1_resources_1_1_order_1_1_config.html", null ],
    [ "MercadoPago\\Resources\\User\\Context", "class_mercado_pago_1_1_resources_1_1_user_1_1_context.html", null ],
    [ "MercadoPago\\Resources\\User\\Credit", "class_mercado_pago_1_1_resources_1_1_user_1_1_credit.html", null ],
    [ "Symfony\\Polyfill\\Ctype\\Ctype", "class_symfony_1_1_polyfill_1_1_ctype_1_1_ctype.html", null ],
    [ "MercadoPago\\Resources\\Customer\\CustomerCardListResult", "class_mercado_pago_1_1_resources_1_1_customer_1_1_customer_card_list_result.html", null ],
    [ "MercadoPago\\Client\\Customer\\CustomerCreateRequest", "class_mercado_pago_1_1_client_1_1_customer_1_1_customer_create_request.html", null ],
    [ "MercadoPago\\Resources\\Customer\\CustomerSearchResult", "class_mercado_pago_1_1_resources_1_1_customer_1_1_customer_search_result.html", null ],
    [ "MercadoPago\\Resources\\User\\DelayedHandlingTime", "class_mercado_pago_1_1_resources_1_1_user_1_1_delayed_handling_time.html", null ],
    [ "MercadoPago\\Resources\\Point\\Device", "class_mercado_pago_1_1_resources_1_1_point_1_1_device.html", null ],
    [ "MercadoPago\\Resources\\Common\\DifferentialPricing", "class_mercado_pago_1_1_resources_1_1_common_1_1_differential_pricing.html", null ],
    [ "Dotenv\\Dotenv", "class_dotenv_1_1_dotenv.html", null ],
    [ "PHPMailer\\PHPMailer\\DSNConfigurator", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_d_s_n_configurator.html", null ],
    [ "Dotenv\\Parser\\Entry", "class_dotenv_1_1_parser_1_1_entry.html", null ],
    [ "Dotenv\\Parser\\EntryParser", "class_dotenv_1_1_parser_1_1_entry_parser.html", null ],
    [ "MercadoPago\\Resources\\Point\\Events", "class_mercado_pago_1_1_resources_1_1_point_1_1_events.html", null ],
    [ "Exception", null, [
      [ "MercadoPago\\Exceptions\\InvalidArgumentException", "class_mercado_pago_1_1_exceptions_1_1_invalid_argument_exception.html", null ],
      [ "MercadoPago\\Exceptions\\MPApiException", "class_mercado_pago_1_1_exceptions_1_1_m_p_api_exception.html", null ],
      [ "PHPMailer\\PHPMailer\\Exception", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_exception.html", null ],
      [ "PHPMailer\\PHPMailer\\Exception", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_exception.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Payment\\Expanded", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded.html", null ],
    [ "MercadoPago\\Resources\\Payment\\ExpandedGateway", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway.html", null ],
    [ "MercadoPago\\Resources\\Payment\\ExpandedGatewayReference", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway_reference.html", null ],
    [ "MercadoPago\\Resources\\Payment\\FeeDetails", "class_mercado_pago_1_1_resources_1_1_payment_1_1_fee_details.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\FinancialInstitutions", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_financial_institutions.html", null ],
    [ "MercadoPago\\Resources\\Payment\\ForwardData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_forward_data.html", null ],
    [ "FPDF", "class_f_p_d_f.html", [
      [ "PDF", "class_p_d_f.html", null ],
      [ "PDF", "class_p_d_f.html", null ],
      [ "PDF", "class_p_d_f.html", null ],
      [ "PDF", "class_p_d_f.html", null ],
      [ "PDF", "class_p_d_f.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Preference\\FreeMethod", "class_mercado_pago_1_1_resources_1_1_preference_1_1_free_method.html", null ],
    [ "MercadoPago\\Resources\\PreApprovalPlan\\FreeTrial", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_free_trial.html", null ],
    [ "GrahamCampbell", null, [
      [ "GrahamCampbell\\ResultType\\Error", "class_graham_campbell_1_1_result_type_1_1_error.html", null ],
      [ "GrahamCampbell\\ResultType\\Success", "class_graham_campbell_1_1_result_type_1_1_success.html", null ]
    ] ],
    [ "MercadoPago\\Net\\HttpMethod", "class_mercado_pago_1_1_net_1_1_http_method.html", null ],
    [ "MercadoPago\\Net\\HttpRequest", "interface_mercado_pago_1_1_net_1_1_http_request.html", [
      [ "MercadoPago\\Net\\CurlRequest", "class_mercado_pago_1_1_net_1_1_curl_request.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Common\\Identification", "class_mercado_pago_1_1_resources_1_1_common_1_1_identification.html", null ],
    [ "MercadoPago\\Resources\\IdentificationType\\IdentificationTypeListResult", "class_mercado_pago_1_1_resources_1_1_identification_type_1_1_identification_type_list_result.html", null ],
    [ "Composer\\InstalledVersions", "class_composer_1_1_installed_versions.html", null ],
    [ "MercadoPago\\Resources\\Order\\IntegrationData", "class_mercado_pago_1_1_resources_1_1_order_1_1_integration_data.html", null ],
    [ "InvalidArgumentException", null, [
      [ "Dotenv\\Exception\\InvalidEncodingException", "class_dotenv_1_1_exception_1_1_invalid_encoding_exception.html", null ],
      [ "Dotenv\\Exception\\InvalidFileException", "class_dotenv_1_1_exception_1_1_invalid_file_exception.html", null ],
      [ "Dotenv\\Exception\\InvalidPathException", "class_dotenv_1_1_exception_1_1_invalid_path_exception.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Order\\InvoicePeriod", "class_mercado_pago_1_1_resources_1_1_order_1_1_invoice_period.html", null ],
    [ "MercadoPago\\Resources\\Invoice\\InvoiceSearchResult", "class_mercado_pago_1_1_resources_1_1_invoice_1_1_invoice_search_result.html", null ],
    [ "MercadoPago\\Resources\\Customer\\Issuer", "class_mercado_pago_1_1_resources_1_1_customer_1_1_issuer.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\Item", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_item.html", null ],
    [ "MercadoPago\\Resources\\Preference\\Item", "class_mercado_pago_1_1_resources_1_1_preference_1_1_item.html", null ],
    [ "MercadoPago\\Resources\\Order\\Items", "class_mercado_pago_1_1_resources_1_1_order_1_1_items.html", null ],
    [ "IteratorAggregate", null, [
      [ "PhpOption\\Option", "class_php_option_1_1_option.html", [
        [ "PhpOption\\LazyOption", "class_php_option_1_1_lazy_option.html", null ],
        [ "PhpOption\\LazyOption", "class_php_option_1_1_lazy_option.html", null ],
        [ "PhpOption\\None", "class_php_option_1_1_none.html", null ],
        [ "PhpOption\\None", "class_php_option_1_1_none.html", null ],
        [ "PhpOption\\Some", "class_php_option_1_1_some.html", null ],
        [ "PhpOption\\Some", "class_php_option_1_1_some.html", null ]
      ] ],
      [ "PhpOption\\Option", "class_php_option_1_1_option.html", null ]
    ] ],
    [ "Dotenv\\Parser\\Lexer", "class_dotenv_1_1_parser_1_1_lexer.html", null ],
    [ "Dotenv\\Parser\\Lines", "class_dotenv_1_1_parser_1_1_lines.html", null ],
    [ "Dotenv\\Loader\\LoaderInterface", "interface_dotenv_1_1_loader_1_1_loader_interface.html", [
      [ "Dotenv\\Loader\\Loader", "class_dotenv_1_1_loader_1_1_loader.html", null ]
    ] ],
    [ "Symfony\\Polyfill\\Mbstring\\Mbstring", "class_symfony_1_1_polyfill_1_1_mbstring_1_1_mbstring.html", null ],
    [ "MercadoPago\\Client\\MercadoPagoClient", "class_mercado_pago_1_1_client_1_1_mercado_pago_client.html", [
      [ "MercadoPago\\Client\\CardToken\\CardTokenClient", "class_mercado_pago_1_1_client_1_1_card_token_1_1_card_token_client.html", null ],
      [ "MercadoPago\\Client\\Customer\\CustomerCardClient", "class_mercado_pago_1_1_client_1_1_customer_1_1_customer_card_client.html", null ],
      [ "MercadoPago\\Client\\Customer\\CustomerClient", "class_mercado_pago_1_1_client_1_1_customer_1_1_customer_client.html", null ],
      [ "MercadoPago\\Client\\IdentificationType\\IdentificationTypeClient", "class_mercado_pago_1_1_client_1_1_identification_type_1_1_identification_type_client.html", null ],
      [ "MercadoPago\\Client\\Invoice\\InvoiceClient", "class_mercado_pago_1_1_client_1_1_invoice_1_1_invoice_client.html", null ],
      [ "MercadoPago\\Client\\MerchantOrder\\MerchantOrderClient", "class_mercado_pago_1_1_client_1_1_merchant_order_1_1_merchant_order_client.html", null ],
      [ "MercadoPago\\Client\\OAuth\\OAuthClient", "class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_client.html", null ],
      [ "MercadoPago\\Client\\Order\\OrderClient", "class_mercado_pago_1_1_client_1_1_order_1_1_order_client.html", null ],
      [ "MercadoPago\\Client\\Order\\OrderTransactionClient", "class_mercado_pago_1_1_client_1_1_order_1_1_order_transaction_client.html", null ],
      [ "MercadoPago\\Client\\Payment\\PaymentClient", "class_mercado_pago_1_1_client_1_1_payment_1_1_payment_client.html", null ],
      [ "MercadoPago\\Client\\Payment\\PaymentRefundClient", "class_mercado_pago_1_1_client_1_1_payment_1_1_payment_refund_client.html", null ],
      [ "MercadoPago\\Client\\PaymentMethod\\PaymentMethodClient", "class_mercado_pago_1_1_client_1_1_payment_method_1_1_payment_method_client.html", null ],
      [ "MercadoPago\\Client\\Point\\PointClient", "class_mercado_pago_1_1_client_1_1_point_1_1_point_client.html", null ],
      [ "MercadoPago\\Client\\PreApproval\\PreApprovalClient", "class_mercado_pago_1_1_client_1_1_pre_approval_1_1_pre_approval_client.html", null ],
      [ "MercadoPago\\Client\\PreApprovalPlan\\PreApprovalPlanClient", "class_mercado_pago_1_1_client_1_1_pre_approval_plan_1_1_pre_approval_plan_client.html", null ],
      [ "MercadoPago\\Client\\Preference\\PreferenceClient", "class_mercado_pago_1_1_client_1_1_preference_1_1_preference_client.html", null ],
      [ "MercadoPago\\Client\\User\\UserClient", "class_mercado_pago_1_1_client_1_1_user_1_1_user_client.html", null ]
    ] ],
    [ "MercadoPago\\MercadoPagoConfig", "class_mercado_pago_1_1_mercado_pago_config.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\MerchantOrderSearchResult", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_merchant_order_search_result.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Metadata", "class_mercado_pago_1_1_resources_1_1_payment_1_1_metadata.html", null ],
    [ "MercadoPago\\Resources\\User\\Metrics", "class_mercado_pago_1_1_resources_1_1_user_1_1_metrics.html", null ],
    [ "MercadoPago\\Net\\MPHttpClient", "interface_mercado_pago_1_1_net_1_1_m_p_http_client.html", [
      [ "MercadoPago\\Net\\MPDefaultHttpClient", "class_mercado_pago_1_1_net_1_1_m_p_default_http_client.html", null ]
    ] ],
    [ "MercadoPago\\Net\\MPRequest", "class_mercado_pago_1_1_net_1_1_m_p_request.html", null ],
    [ "MercadoPago\\Net\\MPResource", "class_mercado_pago_1_1_net_1_1_m_p_resource.html", [
      [ "MercadoPago\\Resources\\CardToken", "class_mercado_pago_1_1_resources_1_1_card_token.html", null ],
      [ "MercadoPago\\Resources\\Customer", "class_mercado_pago_1_1_resources_1_1_customer.html", null ],
      [ "MercadoPago\\Resources\\CustomerCard", "class_mercado_pago_1_1_resources_1_1_customer_card.html", null ],
      [ "MercadoPago\\Resources\\CustomerCardResult", "class_mercado_pago_1_1_resources_1_1_customer_card_result.html", null ],
      [ "MercadoPago\\Resources\\CustomerSearch", "class_mercado_pago_1_1_resources_1_1_customer_search.html", null ],
      [ "MercadoPago\\Resources\\IdentificationTypeResult", "class_mercado_pago_1_1_resources_1_1_identification_type_result.html", null ],
      [ "MercadoPago\\Resources\\Invoice", "class_mercado_pago_1_1_resources_1_1_invoice.html", null ],
      [ "MercadoPago\\Resources\\InvoiceSearch", "class_mercado_pago_1_1_resources_1_1_invoice_search.html", null ],
      [ "MercadoPago\\Resources\\MerchantOrder", "class_mercado_pago_1_1_resources_1_1_merchant_order.html", null ],
      [ "MercadoPago\\Resources\\MerchantOrderSearch", "class_mercado_pago_1_1_resources_1_1_merchant_order_search.html", null ],
      [ "MercadoPago\\Resources\\OAuth", "class_mercado_pago_1_1_resources_1_1_o_auth.html", null ],
      [ "MercadoPago\\Resources\\Order", "class_mercado_pago_1_1_resources_1_1_order.html", null ],
      [ "MercadoPago\\Resources\\Order\\Transaction\\UpdateTransaction", "class_mercado_pago_1_1_resources_1_1_order_1_1_transaction_1_1_update_transaction.html", null ],
      [ "MercadoPago\\Resources\\Order\\Transactions", "class_mercado_pago_1_1_resources_1_1_order_1_1_transactions.html", null ],
      [ "MercadoPago\\Resources\\Payment", "class_mercado_pago_1_1_resources_1_1_payment.html", null ],
      [ "MercadoPago\\Resources\\PaymentIntent", "class_mercado_pago_1_1_resources_1_1_payment_intent.html", null ],
      [ "MercadoPago\\Resources\\PaymentIntentCancel", "class_mercado_pago_1_1_resources_1_1_payment_intent_cancel.html", null ],
      [ "MercadoPago\\Resources\\PaymentIntentList", "class_mercado_pago_1_1_resources_1_1_payment_intent_list.html", null ],
      [ "MercadoPago\\Resources\\PaymentIntentStatus", "class_mercado_pago_1_1_resources_1_1_payment_intent_status.html", null ],
      [ "MercadoPago\\Resources\\PaymentMethodResult", "class_mercado_pago_1_1_resources_1_1_payment_method_result.html", null ],
      [ "MercadoPago\\Resources\\PaymentRefund", "class_mercado_pago_1_1_resources_1_1_payment_refund.html", null ],
      [ "MercadoPago\\Resources\\PaymentRefundResult", "class_mercado_pago_1_1_resources_1_1_payment_refund_result.html", null ],
      [ "MercadoPago\\Resources\\PaymentSearch", "class_mercado_pago_1_1_resources_1_1_payment_search.html", null ],
      [ "MercadoPago\\Resources\\PointDeviceOperatingMode", "class_mercado_pago_1_1_resources_1_1_point_device_operating_mode.html", null ],
      [ "MercadoPago\\Resources\\PointDevices", "class_mercado_pago_1_1_resources_1_1_point_devices.html", null ],
      [ "MercadoPago\\Resources\\PreApproval", "class_mercado_pago_1_1_resources_1_1_pre_approval.html", null ],
      [ "MercadoPago\\Resources\\PreApprovalPlan", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan.html", null ],
      [ "MercadoPago\\Resources\\PreApprovalPlanSearch", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan_search.html", null ],
      [ "MercadoPago\\Resources\\PreApprovalSearch", "class_mercado_pago_1_1_resources_1_1_pre_approval_search.html", null ],
      [ "MercadoPago\\Resources\\Preference", "class_mercado_pago_1_1_resources_1_1_preference.html", null ],
      [ "MercadoPago\\Resources\\Preference\\PreferenceListResult", "class_mercado_pago_1_1_resources_1_1_preference_1_1_preference_list_result.html", null ],
      [ "MercadoPago\\Resources\\PreferenceSearch", "class_mercado_pago_1_1_resources_1_1_preference_search.html", null ],
      [ "MercadoPago\\Resources\\User", "class_mercado_pago_1_1_resources_1_1_user.html", null ]
    ] ],
    [ "MercadoPago\\Net\\MPResponse", "class_mercado_pago_1_1_net_1_1_m_p_response.html", null ],
    [ "MercadoPago\\Net\\MPSearchRequest", "class_mercado_pago_1_1_net_1_1_m_p_search_request.html", null ],
    [ "MercadoPago\\Resources\\Payment\\NetworkTransactionData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_network_transaction_data.html", null ],
    [ "MercadoPago\\Client\\OAuth\\OAuthCreateRequest", "class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_create_request.html", null ],
    [ "MercadoPago\\Client\\OAuth\\OAuthRefreshRequest", "class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_refresh_request.html", null ],
    [ "PHPMailer\\PHPMailer\\OAuthTokenProvider", "interface_p_h_p_mailer_1_1_p_h_p_mailer_1_1_o_auth_token_provider.html", [
      [ "PHPMailer\\PHPMailer\\OAuth", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_o_auth.html", null ],
      [ "PHPMailer\\PHPMailer\\OAuth", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_o_auth.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Order\\OnlineConfig", "class_mercado_pago_1_1_resources_1_1_order_1_1_online_config.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Order", "class_mercado_pago_1_1_resources_1_1_payment_1_1_order.html", null ],
    [ "MercadoPago\\Resources\\Common\\Paging", "class_mercado_pago_1_1_resources_1_1_common_1_1_paging.html", null ],
    [ "Dotenv\\Parser\\ParserInterface", "interface_dotenv_1_1_parser_1_1_parser_interface.html", [
      [ "Dotenv\\Parser\\Parser", "class_dotenv_1_1_parser_1_1_parser.html", null ]
    ] ],
    [ "Dotenv\\Store\\File\\Paths", "class_dotenv_1_1_store_1_1_file_1_1_paths.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\Payer", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_payer.html", null ],
    [ "MercadoPago\\Resources\\Order\\Payer", "class_mercado_pago_1_1_resources_1_1_order_1_1_payer.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Payer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payer.html", null ],
    [ "MercadoPago\\Resources\\Preference\\Payer", "class_mercado_pago_1_1_resources_1_1_preference_1_1_payer.html", null ],
    [ "MercadoPago\\Resources\\Invoice\\Payment", "class_mercado_pago_1_1_resources_1_1_invoice_1_1_payment.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\Payment", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_payment.html", null ],
    [ "MercadoPago\\Resources\\Order\\Payment", "class_mercado_pago_1_1_resources_1_1_order_1_1_payment.html", null ],
    [ "MercadoPago\\Client\\Payment\\PaymentCancelRequest", "class_mercado_pago_1_1_client_1_1_payment_1_1_payment_cancel_request.html", null ],
    [ "MercadoPago\\Client\\Payment\\PaymentCaptureRequest", "class_mercado_pago_1_1_client_1_1_payment_1_1_payment_capture_request.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentDiscounts", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_discounts.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentFee", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_fee.html", null ],
    [ "MercadoPago\\Resources\\Point\\PaymentIntentAdditionalInfo", "class_mercado_pago_1_1_resources_1_1_point_1_1_payment_intent_additional_info.html", null ],
    [ "MercadoPago\\Resources\\Point\\PaymentIntentPayment", "class_mercado_pago_1_1_resources_1_1_point_1_1_payment_intent_payment.html", null ],
    [ "MercadoPago\\Resources\\Customer\\PaymentMethod", "class_mercado_pago_1_1_resources_1_1_customer_1_1_payment_method.html", null ],
    [ "MercadoPago\\Resources\\Order\\PaymentMethod", "class_mercado_pago_1_1_resources_1_1_order_1_1_payment_method.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentMethod", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method.html", null ],
    [ "MercadoPago\\Resources\\Preference\\PaymentMethod", "class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_method.html", null ],
    [ "MercadoPago\\Resources\\Order\\PaymentMethodConfig", "class_mercado_pago_1_1_resources_1_1_order_1_1_payment_method_config.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentMethodData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_data.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\PaymentMethodListResult", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_payment_method_list_result.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentMethodRules", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_rules.html", null ],
    [ "MercadoPago\\Resources\\Preference\\PaymentMethods", "class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_methods.html", null ],
    [ "MercadoPago\\Resources\\PreApprovalPlan\\PaymentMethodsAllowed", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_payment_methods_allowed.html", null ],
    [ "MercadoPago\\Client\\Payment\\PaymentRefundCreateRequest", "class_mercado_pago_1_1_client_1_1_payment_1_1_payment_refund_create_request.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentRefundListResult", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_refund_list_result.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PaymentSearchResult", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_search_result.html", null ],
    [ "MercadoPago\\Resources\\Preference\\PaymentType", "class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_type.html", null ],
    [ "MercadoPago\\Resources\\Common\\Phone", "class_mercado_pago_1_1_resources_1_1_common_1_1_phone.html", [
      [ "MercadoPago\\Resources\\User\\Phone", "class_mercado_pago_1_1_resources_1_1_user_1_1_phone.html", null ]
    ] ],
    [ "Symfony\\Polyfill\\Php80\\Php80", "class_symfony_1_1_polyfill_1_1_php80_1_1_php80.html", null ],
    [ "PHPMailer\\PHPMailer\\PHPMailer", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html", null ],
    [ "MercadoPago\\Client\\Point\\PointDeviceOperatingModeRequest", "class_mercado_pago_1_1_client_1_1_point_1_1_point_device_operating_mode_request.html", null ],
    [ "MercadoPago\\Resources\\Payment\\PointOfInteraction", "class_mercado_pago_1_1_resources_1_1_payment_1_1_point_of_interaction.html", null ],
    [ "MercadoPago\\Client\\Point\\PointPaymentIntentListRequest", "class_mercado_pago_1_1_client_1_1_point_1_1_point_payment_intent_list_request.html", null ],
    [ "PHPMailer\\PHPMailer\\POP3", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_o_p3.html", null ],
    [ "MercadoPago\\Resources\\PreApproval\\PreApprovalListResult", "class_mercado_pago_1_1_resources_1_1_pre_approval_1_1_pre_approval_list_result.html", null ],
    [ "MercadoPago\\Resources\\PreApprovalPlan\\PreApprovalPlanListResult", "class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_pre_approval_plan_list_result.html", null ],
    [ "MercadoPago\\Resources\\User\\Ratings", "class_mercado_pago_1_1_resources_1_1_user_1_1_ratings.html", null ],
    [ "Dotenv\\Store\\File\\Reader", "class_dotenv_1_1_store_1_1_file_1_1_reader.html", null ],
    [ "Dotenv\\Repository\\Adapter\\ReaderInterface", "interface_dotenv_1_1_repository_1_1_adapter_1_1_reader_interface.html", [
      [ "Dotenv\\Repository\\Adapter\\AdapterInterface", "interface_dotenv_1_1_repository_1_1_adapter_1_1_adapter_interface.html", [
        [ "Dotenv\\Repository\\Adapter\\ApacheAdapter", "class_dotenv_1_1_repository_1_1_adapter_1_1_apache_adapter.html", null ],
        [ "Dotenv\\Repository\\Adapter\\ArrayAdapter", "class_dotenv_1_1_repository_1_1_adapter_1_1_array_adapter.html", null ],
        [ "Dotenv\\Repository\\Adapter\\EnvConstAdapter", "class_dotenv_1_1_repository_1_1_adapter_1_1_env_const_adapter.html", null ],
        [ "Dotenv\\Repository\\Adapter\\PutenvAdapter", "class_dotenv_1_1_repository_1_1_adapter_1_1_putenv_adapter.html", null ],
        [ "Dotenv\\Repository\\Adapter\\ServerConstAdapter", "class_dotenv_1_1_repository_1_1_adapter_1_1_server_const_adapter.html", null ]
      ] ],
      [ "Dotenv\\Repository\\Adapter\\MultiReader", "class_dotenv_1_1_repository_1_1_adapter_1_1_multi_reader.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ReceiverAddress", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_receiver_address.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ReceiverAddressCity", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_receiver_address_city.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ReceiverAddressCountry", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_receiver_address_country.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ReceiverAddressState", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_receiver_address_state.html", null ],
    [ "MercadoPago\\Resources\\Order\\Refund", "class_mercado_pago_1_1_resources_1_1_order_1_1_refund.html", null ],
    [ "Dotenv\\Util\\Regex", "class_dotenv_1_1_util_1_1_regex.html", null ],
    [ "Dotenv\\Repository\\RepositoryBuilder", "class_dotenv_1_1_repository_1_1_repository_builder.html", null ],
    [ "Dotenv\\Repository\\RepositoryInterface", "interface_dotenv_1_1_repository_1_1_repository_interface.html", [
      [ "Dotenv\\Repository\\AdapterRepository", "class_dotenv_1_1_repository_1_1_adapter_repository.html", null ]
    ] ],
    [ "MercadoPago\\Client\\Common\\RequestOptions", "class_mercado_pago_1_1_client_1_1_common_1_1_request_options.html", null ],
    [ "Dotenv\\Loader\\Resolver", "class_dotenv_1_1_loader_1_1_resolver.html", null ],
    [ "GrahamCampbell\\ResultType\\Result", "class_graham_campbell_1_1_result_type_1_1_result.html", [
      [ "GrahamCampbell\\ResultType\\Error", "class_graham_campbell_1_1_result_type_1_1_error.html", null ],
      [ "GrahamCampbell\\ResultType\\Success", "class_graham_campbell_1_1_result_type_1_1_success.html", null ]
    ] ],
    [ "RuntimeException", null, [
      [ "Dotenv\\Exception\\ValidationException", "class_dotenv_1_1_exception_1_1_validation_exception.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\User\\Sales", "class_mercado_pago_1_1_resources_1_1_user_1_1_sales.html", null ],
    [ "MercadoPago\\Resources\\Customer\\SecurityCode", "class_mercado_pago_1_1_resources_1_1_customer_1_1_security_code.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\SecurityCode", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_security_code.html", null ],
    [ "MercadoPago\\Resources\\User\\SellerReputation", "class_mercado_pago_1_1_resources_1_1_user_1_1_seller_reputation.html", null ],
    [ "MercadoPago\\Serialization\\Serializer", "class_mercado_pago_1_1_serialization_1_1_serializer.html", null ],
    [ "MercadoPago\\Resources\\PaymentMethod\\Settings", "class_mercado_pago_1_1_resources_1_1_payment_method_1_1_settings.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\Shipment", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_shipment.html", null ],
    [ "MercadoPago\\Resources\\Payment\\Shipments", "class_mercado_pago_1_1_resources_1_1_payment_1_1_shipments.html", null ],
    [ "MercadoPago\\Resources\\Preference\\Shipments", "class_mercado_pago_1_1_resources_1_1_preference_1_1_shipments.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ShippingEstimatedDelivery", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_shipping_estimated_delivery.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ShippingOption", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_shipping_option.html", null ],
    [ "MercadoPago\\Resources\\MerchantOrder\\ShippingSpeed", "class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_shipping_speed.html", null ],
    [ "PHPMailer\\PHPMailer\\SMTP", "class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html", null ],
    [ "MercadoPago\\Resources\\Common\\Source", "class_mercado_pago_1_1_resources_1_1_common_1_1_source.html", null ],
    [ "MercadoPago\\Resources\\Order\\Sponsor", "class_mercado_pago_1_1_resources_1_1_order_1_1_sponsor.html", null ],
    [ "MercadoPago\\Resources\\User\\Status", "class_mercado_pago_1_1_resources_1_1_user_1_1_status.html", null ],
    [ "MercadoPago\\Resources\\User\\StatusBilling", "class_mercado_pago_1_1_resources_1_1_user_1_1_status_billing.html", null ],
    [ "MercadoPago\\Resources\\User\\StatusBuyImmediatePayment", "class_mercado_pago_1_1_resources_1_1_user_1_1_status_buy_immediate_payment.html", null ],
    [ "MercadoPago\\Resources\\User\\StatusList", "class_mercado_pago_1_1_resources_1_1_user_1_1_status_list.html", null ],
    [ "MercadoPago\\Resources\\User\\StatusShoppingCart", "class_mercado_pago_1_1_resources_1_1_user_1_1_status_shopping_cart.html", null ],
    [ "Dotenv\\Store\\StoreBuilder", "class_dotenv_1_1_store_1_1_store_builder.html", null ],
    [ "MercadoPago\\Resources\\Order\\StoredCredential", "class_mercado_pago_1_1_resources_1_1_order_1_1_stored_credential.html", null ],
    [ "Dotenv\\Store\\StoreInterface", "interface_dotenv_1_1_store_1_1_store_interface.html", [
      [ "Dotenv\\Store\\FileStore", "class_dotenv_1_1_store_1_1_file_store.html", null ],
      [ "Dotenv\\Store\\StringStore", "class_dotenv_1_1_store_1_1_string_store.html", null ]
    ] ],
    [ "Dotenv\\Util\\Str", "class_dotenv_1_1_util_1_1_str.html", null ],
    [ "Stringable", null, [
      [ "Symfony\\Polyfill\\Php80\\PhpToken", "class_symfony_1_1_polyfill_1_1_php80_1_1_php_token.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Common\\SubMerchant", "class_mercado_pago_1_1_resources_1_1_common_1_1_sub_merchant.html", null ],
    [ "MercadoPago\\Resources\\Order\\SubscriptionData", "class_mercado_pago_1_1_resources_1_1_order_1_1_subscription_data.html", null ],
    [ "MercadoPago\\Resources\\Order\\SubscriptionSequence", "class_mercado_pago_1_1_resources_1_1_order_1_1_subscription_sequence.html", null ],
    [ "MercadoPago\\Resources\\PreApproval\\Summarized", "class_mercado_pago_1_1_resources_1_1_pre_approval_1_1_summarized.html", null ],
    [ "MercadoPago\\Resources\\Preference\\Tax", "class_mercado_pago_1_1_resources_1_1_preference_1_1_tax.html", null ],
    [ "TestCase", null, [
      [ "MercadoPago\\Tests\\Client\\Integration\\CardToken\\CardTokenClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_card_token_1_1_card_token_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Customer\\CustomerCardClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_card_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Customer\\CustomerClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\IdentificationType\\IdentificationTypeClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_identification_type_1_1_identification_type_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\MerchantOrder\\MerchantOrderClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_merchant_order_1_1_merchant_order_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Order\\OrderClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Order\\OrderTransactionClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_transaction_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Payment\\PaymentClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_1_1_payment_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Payment\\PaymentRefundClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_1_1_payment_refund_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\PaymentMethod\\PaymentMethodClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_method_1_1_payment_method_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Point\\PointClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_point_1_1_point_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\PreApproval\\PreApprovalClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_1_1_pre_approval_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\PreApprovalPlan\\PreApprovalPlanClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_plan_1_1_pre_approval_plan_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\Preference\\PreferenceClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_preference_1_1_preference_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Integration\\User\\UserClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_user_1_1_user_client_i_t_test.html", null ],
      [ "MercadoPago\\Tests\\Client\\Unit\\Base\\BaseClient", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_base_1_1_base_client.html", [
        [ "MercadoPago\\Tests\\Client\\Unit\\CardToken\\CardTokenClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_card_token_1_1_card_token_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Customer\\CustomerCardClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_card_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Customer\\CustomerClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\IdentificationType\\IdentificationTypeClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_identification_type_1_1_identification_type_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Invoice\\InvoiceClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_invoice_1_1_invoice_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\MerchantOrder\\MerchantOrderClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_merchant_order_1_1_merchant_order_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\OAuth\\OAuthClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_o_auth_1_1_o_auth_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Order\\OrderClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Order\\OrderTransactionClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_transaction_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Payment\\PaymentClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_1_1_payment_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Payment\\PaymentRefundClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_1_1_payment_refund_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\PaymentMethod\\PaymentMethodClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_method_1_1_payment_method_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Point\\PointClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_point_1_1_point_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\PreApproval\\PreApprovalClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_pre_approval_1_1_pre_approval_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\PreApprovalPlan\\PreApprovalPlanClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_pre_approval_plan_1_1_pre_approval_plan_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\Preference\\PreferenceClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_preference_1_1_preference_client_unit_test.html", null ],
        [ "MercadoPago\\Tests\\Client\\Unit\\User\\UserClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_user_1_1_user_client_unit_test.html", null ]
      ] ],
      [ "MercadoPago\\Tests\\MercadoPagoConfigTest", "class_mercado_pago_1_1_tests_1_1_mercado_pago_config_test.html", null ]
    ] ],
    [ "MercadoPago\\Resources\\Payment\\ThreeDSInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_three_d_s_info.html", null ],
    [ "Throwable", null, [
      [ "Dotenv\\Exception\\ExceptionInterface", "interface_dotenv_1_1_exception_1_1_exception_interface.html", [
        [ "Dotenv\\Exception\\InvalidEncodingException", "class_dotenv_1_1_exception_1_1_invalid_encoding_exception.html", null ],
        [ "Dotenv\\Exception\\InvalidFileException", "class_dotenv_1_1_exception_1_1_invalid_file_exception.html", null ],
        [ "Dotenv\\Exception\\InvalidPathException", "class_dotenv_1_1_exception_1_1_invalid_path_exception.html", null ],
        [ "Dotenv\\Exception\\ValidationException", "class_dotenv_1_1_exception_1_1_validation_exception.html", null ]
      ] ]
    ] ],
    [ "MercadoPago\\Resources\\Preference\\Track", "class_mercado_pago_1_1_resources_1_1_preference_1_1_track.html", null ],
    [ "MercadoPago\\Resources\\Preference\\TrackValues", "class_mercado_pago_1_1_resources_1_1_preference_1_1_track_values.html", null ],
    [ "MercadoPago\\Resources\\Payment\\TransactionData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_data.html", null ],
    [ "MercadoPago\\Resources\\Payment\\TransactionDetails", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_details.html", null ],
    [ "MercadoPago\\Resources\\User\\Transactions", "class_mercado_pago_1_1_resources_1_1_user_1_1_transactions.html", null ],
    [ "TTFParser", "class_t_t_f_parser.html", null ],
    [ "MercadoPago\\Resources\\Preference\\Urls", "class_mercado_pago_1_1_resources_1_1_preference_1_1_urls.html", [
      [ "MercadoPago\\Resources\\Preference\\BackUrls", "class_mercado_pago_1_1_resources_1_1_preference_1_1_back_urls.html", null ],
      [ "MercadoPago\\Resources\\Preference\\RedirectUrls", "class_mercado_pago_1_1_resources_1_1_preference_1_1_redirect_urls.html", null ]
    ] ],
    [ "Dotenv\\Validator", "class_dotenv_1_1_validator.html", null ],
    [ "Dotenv\\Parser\\Value", "class_dotenv_1_1_parser_1_1_value.html", null ],
    [ "Dotenv\\Repository\\Adapter\\WriterInterface", "interface_dotenv_1_1_repository_1_1_adapter_1_1_writer_interface.html", [
      [ "Dotenv\\Repository\\Adapter\\AdapterInterface", "interface_dotenv_1_1_repository_1_1_adapter_1_1_adapter_interface.html", null ],
      [ "Dotenv\\Repository\\Adapter\\GuardedWriter", "class_dotenv_1_1_repository_1_1_adapter_1_1_guarded_writer.html", null ],
      [ "Dotenv\\Repository\\Adapter\\ImmutableWriter", "class_dotenv_1_1_repository_1_1_adapter_1_1_immutable_writer.html", null ],
      [ "Dotenv\\Repository\\Adapter\\MultiWriter", "class_dotenv_1_1_repository_1_1_adapter_1_1_multi_writer.html", null ],
      [ "Dotenv\\Repository\\Adapter\\ReplacingWriter", "class_dotenv_1_1_repository_1_1_adapter_1_1_replacing_writer.html", null ]
    ] ]
];