var namespace_mercado_pago_1_1_resources_1_1_payment =
[
    [ "AdditionalInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info" ],
    [ "AdditionalInfoPayer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info_payer.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_additional_info_payer" ],
    [ "ApplicationData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_application_data.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_application_data" ],
    [ "BankInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info" ],
    [ "BankInfoCollector", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_collector.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_collector" ],
    [ "BankInfoPayer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_payer.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_payer" ],
    [ "Barcode", "class_mercado_pago_1_1_resources_1_1_payment_1_1_barcode.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_barcode" ],
    [ "Card", "class_mercado_pago_1_1_resources_1_1_payment_1_1_card.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_card" ],
    [ "Cardholder", "class_mercado_pago_1_1_resources_1_1_payment_1_1_cardholder.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_cardholder" ],
    [ "Expanded", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded" ],
    [ "ExpandedGateway", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway" ],
    [ "ExpandedGatewayReference", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway_reference.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_expanded_gateway_reference" ],
    [ "FeeDetails", "class_mercado_pago_1_1_resources_1_1_payment_1_1_fee_details.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_fee_details" ],
    [ "ForwardData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_forward_data.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_forward_data" ],
    [ "Metadata", "class_mercado_pago_1_1_resources_1_1_payment_1_1_metadata.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_metadata" ],
    [ "NetworkTransactionData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_network_transaction_data.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_network_transaction_data" ],
    [ "Order", "class_mercado_pago_1_1_resources_1_1_payment_1_1_order.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_order" ],
    [ "Payer", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payer.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payer" ],
    [ "PaymentDiscounts", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_discounts.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_discounts" ],
    [ "PaymentFee", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_fee.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_fee" ],
    [ "PaymentMethod", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method" ],
    [ "PaymentMethodData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_data.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_data" ],
    [ "PaymentMethodRules", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_rules.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_rules" ],
    [ "PaymentRefundListResult", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_refund_list_result.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_refund_list_result" ],
    [ "PaymentSearchResult", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_search_result.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_search_result" ],
    [ "PointOfInteraction", "class_mercado_pago_1_1_resources_1_1_payment_1_1_point_of_interaction.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_point_of_interaction" ],
    [ "ReceiverAddress", "class_mercado_pago_1_1_resources_1_1_payment_1_1_receiver_address.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_receiver_address" ],
    [ "Shipments", "class_mercado_pago_1_1_resources_1_1_payment_1_1_shipments.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_shipments" ],
    [ "ThreeDSInfo", "class_mercado_pago_1_1_resources_1_1_payment_1_1_three_d_s_info.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_three_d_s_info" ],
    [ "TransactionData", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_data.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_data" ],
    [ "TransactionDetails", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_details.html", "class_mercado_pago_1_1_resources_1_1_payment_1_1_transaction_details" ]
];