var namespace_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order =
[
    [ "OrderClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_client_i_t_test" ],
    [ "OrderTransactionClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_transaction_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_transaction_client_i_t_test" ]
];