var namespace_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer =
[
    [ "CustomerCardClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_card_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_card_client_i_t_test" ],
    [ "CustomerClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_customer_1_1_customer_client_i_t_test" ]
];