var namespace_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order =
[
    [ "OrderClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_client_unit_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_client_unit_test" ],
    [ "OrderTransactionClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_transaction_client_unit_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_transaction_client_unit_test" ]
];