var namespace_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer =
[
    [ "CustomerCardClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_card_client_unit_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_card_client_unit_test" ],
    [ "CustomerClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_client_unit_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_customer_1_1_customer_client_unit_test" ]
];