var namespace_mercado_pago_1_1_client_1_1_identification_type =
[
    [ "IdentificationTypeClient", "class_mercado_pago_1_1_client_1_1_identification_type_1_1_identification_type_client.html", "class_mercado_pago_1_1_client_1_1_identification_type_1_1_identification_type_client" ]
];