var namespace_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_point =
[
    [ "PointClientUnitTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_point_1_1_point_client_unit_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_point_1_1_point_client_unit_test" ]
];