var namespace_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_user =
[
    [ "UserClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_user_1_1_user_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_user_1_1_user_client_i_t_test" ]
];