var namespace_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_point =
[
    [ "PointClientITTest", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_point_1_1_point_client_i_t_test.html", "class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_point_1_1_point_client_i_t_test" ]
];