var searchData=
[
  ['unhandledmatcherror_2ephp_0',['UnhandledMatchError.php',['../_unhandled_match_error_8php.html',1,'']]],
  ['unregister_1',['unregister',['../class_composer_1_1_autoload_1_1_class_loader.html#a2472d57551ee473381beea31ff642136',1,'Composer::Autoload::ClassLoader']]],
  ['update_2',['Dependency Update',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md107',1,'']]],
  ['update_3',['update',['../class_mercado_pago_1_1_client_1_1_customer_1_1_customer_card_client.html#af1ab137a57a56c1e931f61dc6fb609be',1,'MercadoPago\Client\Customer\CustomerCardClient\update()'],['../class_mercado_pago_1_1_client_1_1_customer_1_1_customer_client.html#a132c50a9710465c87227ed6cfd7f494c',1,'MercadoPago\Client\Customer\CustomerClient\update()'],['../class_mercado_pago_1_1_client_1_1_merchant_order_1_1_merchant_order_client.html#a1eb56cef7ced33fda83f414648627ca7',1,'MercadoPago\Client\MerchantOrder\MerchantOrderClient\update()'],['../class_mercado_pago_1_1_client_1_1_order_1_1_order_transaction_client.html#a773ef3713f19de895164238530572182',1,'MercadoPago\Client\Order\OrderTransactionClient\update()'],['../class_mercado_pago_1_1_client_1_1_pre_approval_1_1_pre_approval_client.html#a9257d5f0509d15940d7829972d699944',1,'MercadoPago\Client\PreApproval\PreApprovalClient\update()'],['../class_mercado_pago_1_1_client_1_1_pre_approval_plan_1_1_pre_approval_plan_client.html#a1f9f938702bfd783084bd29c95167398',1,'MercadoPago\Client\PreApprovalPlan\PreApprovalPlanClient\update()'],['../class_mercado_pago_1_1_client_1_1_preference_1_1_preference_client.html#a3e3b8a8830fe4faebc030d3c101cef02',1,'MercadoPago\Client\Preference\PreferenceClient\update()']]],
  ['update_20exception_20handling_4',['Step 4: Update exception handling',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md113',1,'']]],
  ['update_20imports_5',['Step 2: Update Imports',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md111',1,'']]],
  ['update_20methods_6',['Step 3: Update Methods',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md112',1,'']]],
  ['update_2ephp_7',['Update.php',['../_update_8php.html',1,'']]],
  ['update_5fpreferencias_2ephp_8',['update_preferencias.php',['../update__preferencias_8php.html',1,'']]],
  ['updatetransaction_9',['UpdateTransaction',['../class_mercado_pago_1_1_resources_1_1_order_1_1_transaction_1_1_update_transaction.html',1,'MercadoPago::Resources::Order::Transaction']]],
  ['updatetransaction_2ephp_10',['UpdateTransaction.php',['../_update_transaction_8php.html',1,'']]],
  ['upgrading_20from_205_202_11',['Upgrading from 5 2',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md49',1,'Upgrading from 5.2'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md148',1,'Upgrading from 5.2']]],
  ['uppercase_2ephp_12',['upperCase.php',['../upper_case_8php.html',1,'']]],
  ['urls_13',['Urls',['../class_mercado_pago_1_1_resources_1_1_preference_1_1_urls.html',1,'MercadoPago::Resources::Preference']]],
  ['urls_2ephp_14',['Urls.php',['../_urls_8php.html',1,'']]],
  ['use_20of_20composer_15',['Use of Composer',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md108',1,'']]],
  ['useful_20links_16',['Useful links',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md123',1,'']]],
  ['user_17',['User',['../class_mercado_pago_1_1_resources_1_1_user.html',1,'MercadoPago::Resources']]],
  ['user_2ephp_18',['User.php',['../_user_8php.html',1,'']]],
  ['userclient_19',['UserClient',['../class_mercado_pago_1_1_client_1_1_user_1_1_user_client.html',1,'MercadoPago::Client::User']]],
  ['userclient_2ephp_20',['UserClient.php',['../_user_client_8php.html',1,'']]],
  ['userclientittest_21',['UserClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_user_1_1_user_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::User']]],
  ['userclientittest_2ephp_22',['UserClientITTest.php',['../_user_client_i_t_test_8php.html',1,'']]],
  ['userclientunittest_23',['UserClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_user_1_1_user_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::User']]],
  ['userclientunittest_2ephp_24',['UserClientUnitTest.php',['../_user_client_unit_test_8php.html',1,'']]],
  ['usuario_20actualizar_5fusuario_20php_25',['Actualizar Usuario (actualizar_usuario.php)',['../endpoints.html#actualizar',1,'']]],
  ['usuario_20en_20la_20base_20de_20datos_26',['Consultar usuario en la base de datos',['../procesar__registro_8php.html#paso4',1,'']]],
  ['usuario_20guardar_5fpreferencia_20php_27',['Preferencias del Usuario (guardar_preferencia.php)',['../endpoints.html#preferencias',1,'']]],
  ['usuario_20obtener_5fusuario_20php_28',['Obtener Usuario (obtener_usuario.php)',['../endpoints.html#obtener',1,'']]],
  ['usuario_20register_20php_29',['Registro de Usuario (register.php)',['../endpoints.html#registro',1,'']]],
  ['usuarios_30',['Autenticación de Usuarios',['../index.html#autotoc_md82',1,'']]],
  ['utf_208_20in_20email_31',['UTF 8 in email',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email']]],
  ['utf8charboundary_32',['utf8CharBoundary',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#abc9948dedc04830eaea5462c0ade83ad',1,'PHPMailer\PHPMailer\PHPMailer\utf8CharBoundary($encodedText, $maxLength)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#abc9948dedc04830eaea5462c0ade83ad',1,'PHPMailer\PHPMailer\PHPMailer\utf8CharBoundary($encodedText, $maxLength)']]],
  ['utilidades_33',['Documentación y utilidades',['../index.html#autotoc_md78',1,'']]],
  ['utilizadas_34',['⚙️ Tecnologías Utilizadas',['../index.html#autotoc_md72',1,'']]],
  ['utilizadas_20en_20el_20proceso_35',['Variables utilizadas en el proceso',['../procesar__registro_8php.html#variables',1,'']]]
];
