var searchData=
[
  ['o_20l_20e_20—_20documento_20visual_20y_20técnico_0',['Endpoints N.I.C.O.L.E — Documento visual y técnico',['../endpoints.html',1,'']]],
  ['o_20l_20e_20versión_20web_1',['Proyecto N.I.C.O.L.E Versión Web',['../index.html',1,'']]],
  ['oauth_2',['OAuth',['../class_mercado_pago_1_1_resources_1_1_o_auth.html',1,'MercadoPago\Resources\OAuth'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_o_auth.html',1,'PHPMailer\PHPMailer\OAuth']]],
  ['oauth_2ephp_3',['OAuth.php',['../libs_2_p_h_p_mailer_2src_2_o_auth_8php.html',1,'(Espacio de nombres global)'],['../vendor_2mercadopago_2dx-php_2src_2_mercado_pago_2_resources_2_o_auth_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2src_2_o_auth_8php.html',1,'(Espacio de nombres global)']]],
  ['oauthclient_4',['OAuthClient',['../class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_client.html',1,'MercadoPago::Client::OAuth']]],
  ['oauthclient_2ephp_5',['OAuthClient.php',['../_o_auth_client_8php.html',1,'']]],
  ['oauthclientunittest_6',['OAuthClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_o_auth_1_1_o_auth_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::OAuth']]],
  ['oauthclientunittest_2ephp_7',['OAuthClientUnitTest.php',['../_o_auth_client_unit_test_8php.html',1,'']]],
  ['oauthcreaterequest_8',['OAuthCreateRequest',['../class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_create_request.html',1,'MercadoPago::Client::OAuth']]],
  ['oauthcreaterequest_2ephp_9',['OAuthCreateRequest.php',['../_o_auth_create_request_8php.html',1,'']]],
  ['oauthrefreshrequest_10',['OAuthRefreshRequest',['../class_mercado_pago_1_1_client_1_1_o_auth_1_1_o_auth_refresh_request.html',1,'MercadoPago::Client::OAuth']]],
  ['oauthrefreshrequest_2ephp_11',['OAuthRefreshRequest.php',['../_o_auth_refresh_request_8php.html',1,'']]],
  ['oauthtokenprovider_12',['OAuthTokenProvider',['../interface_p_h_p_mailer_1_1_p_h_p_mailer_1_1_o_auth_token_provider.html',1,'PHPMailer::PHPMailer']]],
  ['oauthtokenprovider_2ephp_13',['OAuthTokenProvider.php',['../libs_2_p_h_p_mailer_2src_2_o_auth_token_provider_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2src_2_o_auth_token_provider_8php.html',1,'(Espacio de nombres global)']]],
  ['objetivo_20del_20proyecto_14',['🎯 Objetivo del Proyecto',['../index.html#autotoc_md70',1,'']]],
  ['obsoletos_15',['Lista de obsoletos',['../deprecated.html',1,'']]],
  ['obtener_20usuario_20obtener_5fusuario_20php_16',['Obtener Usuario (obtener_usuario.php)',['../endpoints.html#obtener',1,'']]],
  ['obtener_5fusuario_20php_17',['Obtener Usuario (obtener_usuario.php)',['../endpoints.html#obtener',1,'']]],
  ['occurrences_18',['occurrences',['../class_dotenv_1_1_util_1_1_regex.html#a795b3d5dad7406939ce3a6e949f96928',1,'Dotenv::Util::Regex']]],
  ['of_20composer_19',['Use of Composer',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md108',1,'']]],
  ['of_20utf_208_20in_20email_20',['of UTF 8 in email',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email']]],
  ['on_20mercado_20pago_20docs_21',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['onlineconfig_22',['OnlineConfig',['../class_mercado_pago_1_1_resources_1_1_order_1_1_online_config.html',1,'MercadoPago::Resources::Order']]],
  ['onlineconfig_2ephp_23',['OnlineConfig.php',['../_online_config_8php.html',1,'']]],
  ['opentag_24',['OpenTag',['../class_p_d_f.html#a2c96493c42bc1d07268194e303fbf87f',1,'PDF']]],
  ['option_25',['Option',['../class_php_option_1_1_option.html',1,'PhpOption']]],
  ['option_2ephp_26',['Option.php',['../_option_8php.html',1,'']]],
  ['options_20setting_20x_20idempotency_20key_27',['Step 5: Create the request options, setting X-Idempotency-Key',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md129',1,'']]],
  ['or_20sandbox_20access_20token_28',['Step 2: Set production or sandbox access token',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md126',1,'']]],
  ['order_29',['Order',['../class_mercado_pago_1_1_resources_1_1_order.html',1,'MercadoPago\Resources\Order'],['../class_mercado_pago_1_1_resources_1_1_payment_1_1_order.html',1,'MercadoPago\Resources\Payment\Order']]],
  ['order_2ephp_30',['Order.php',['../_order_8php.html',1,'(Espacio de nombres global)'],['../_payment_2_order_8php.html',1,'(Espacio de nombres global)']]],
  ['orderclient_31',['OrderClient',['../class_mercado_pago_1_1_client_1_1_order_1_1_order_client.html',1,'MercadoPago::Client::Order']]],
  ['orderclient_2ephp_32',['OrderClient.php',['../_order_client_8php.html',1,'']]],
  ['orderclientittest_33',['OrderClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Order']]],
  ['orderclientittest_2ephp_34',['OrderClientITTest.php',['../_order_client_i_t_test_8php.html',1,'']]],
  ['orderclientunittest_35',['OrderClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Order']]],
  ['orderclientunittest_2ephp_36',['OrderClientUnitTest.php',['../_order_client_unit_test_8php.html',1,'']]],
  ['ordertransactionclient_37',['OrderTransactionClient',['../class_mercado_pago_1_1_client_1_1_order_1_1_order_transaction_client.html',1,'MercadoPago::Client::Order']]],
  ['ordertransactionclient_2ephp_38',['OrderTransactionClient.php',['../_order_transaction_client_8php.html',1,'']]],
  ['ordertransactionclientittest_39',['OrderTransactionClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_order_1_1_order_transaction_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Order']]],
  ['ordertransactionclientittest_2ephp_40',['OrderTransactionClientITTest.php',['../_order_transaction_client_i_t_test_8php.html',1,'']]],
  ['ordertransactionclientunittest_41',['OrderTransactionClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_order_1_1_order_transaction_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Order']]],
  ['ordertransactionclientunittest_2ephp_42',['OrderTransactionClientUnitTest.php',['../_order_transaction_client_unit_test_8php.html',1,'']]],
  ['orelse_43',['orElse',['../class_php_option_1_1_lazy_option.html#ad7685c72601a629bb2bab725953f8ce7',1,'PhpOption\LazyOption\orElse()'],['../class_php_option_1_1_none.html#a0c7c5e7225e5a683adba4cf5189c783c',1,'PhpOption\None\orElse()'],['../class_php_option_1_1_option.html#a99b5b38bebb3b33a2bc33854250649ec',1,'PhpOption\Option\orElse()'],['../class_php_option_1_1_some.html#a2ece4a03841d4543e348ee98c1def134',1,'PhpOption\Some\orElse()']]],
  ['other_2ephp_44',['other.php',['../other_8php.html',1,'']]],
  ['output_45',['Output',['../class_f_p_d_f.html#ae5700d4b1acede42262d383d9986de90',1,'FPDF']]],
  ['own_20website_20forms_46',['🌟 Getting Started with payment via your own website forms',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md124',1,'']]]
];
