var searchData=
[
  ['v2_20to_20v3_0',['Migration Guide from MercadoPago PHP SDK v2 to v3',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['v3_1',['Migration Guide from MercadoPago PHP SDK v2 to v3',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['validaciones_2ephp_2',['validaciones.php',['../validaciones_8php.html',1,'']]],
  ['validar_20correo_3',['Validar correo',['../procesar__registro_8php.html#paso3',1,'']]],
  ['validarcorreo_4',['validarCorreo',['../validaciones_8php.html#a61c6731c6de20d45ab3bfeaba4b28ad1',1,'validaciones.php']]],
  ['validarpassword_5',['validarPassword',['../validaciones_8php.html#a3ad9b9e20da874f35a6efa052c8e714c',1,'validaciones.php']]],
  ['validateaddress_6',['validateAddress',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#abc9724fcd40217503b3dcb5062791e3b',1,'PHPMailer\PHPMailer\PHPMailer\validateAddress($address, $patternselect=null)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#abc9724fcd40217503b3dcb5062791e3b',1,'PHPMailer\PHPMailer\PHPMailer\validateAddress($address, $patternselect=null)']]],
  ['validateencoding_7',['validateEncoding',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#ace406e09f9eada020abdac1e396ee426',1,'PHPMailer\PHPMailer\PHPMailer\validateEncoding($encoding)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#ace406e09f9eada020abdac1e396ee426',1,'PHPMailer\PHPMailer\PHPMailer\validateEncoding($encoding)']]],
  ['validation_20checklist_3a_8',['PR validation checklist:',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html#autotoc_md119',1,'']]],
  ['validationexception_9',['ValidationException',['../class_dotenv_1_1_exception_1_1_validation_exception.html',1,'Dotenv::Exception']]],
  ['validationexception_2ephp_10',['ValidationException.php',['../_validation_exception_8php.html',1,'']]],
  ['validator_11',['Validator',['../class_dotenv_1_1_validator.html',1,'Dotenv']]],
  ['validator_2ephp_12',['Validator.php',['../_validator_8php.html',1,'']]],
  ['value_13',['Value',['../class_dotenv_1_1_parser_1_1_value.html',1,'Dotenv::Parser']]],
  ['value_2ephp_14',['Value.php',['../_value_8php.html',1,'']]],
  ['valueerror_2ephp_15',['ValueError.php',['../_value_error_8php.html',1,'']]],
  ['variables_20utilizadas_20en_20el_20proceso_16',['Variables utilizadas en el proceso',['../procesar__registro_8php.html#variables',1,'']]],
  ['varset_2ephp_17',['varset.php',['../varset_8php.html',1,'']]],
  ['vendor_20folder_18',['Step 1: Require the library from your Composer vendor folder',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md125',1,'']]],
  ['verificación_20reenviar_5fcodigo_20php_19',['Reenviar Código de Verificación (reenviar_codigo.php)',['../endpoints.html#reenviar',1,'']]],
  ['verificar_20código_20verificar_20php_20',['Verificar Código (verificar.php)',['../endpoints.html#verificar',1,'']]],
  ['verificar_20contraseña_20y_20guardar_20sesión_21',['Verificar contraseña y guardar sesión',['../procesar__registro_8php.html#paso5',1,'']]],
  ['verificar_20método_20post_22',['Verificar método POST',['../procesar__registro_8php.html#paso1',1,'']]],
  ['verificar_20php_23',['Verificar Código (verificar.php)',['../endpoints.html#verificar',1,'']]],
  ['verificar_2ephp_24',['verificar.php',['../api_2verificar_8php.html',1,'(Espacio de nombres global)'],['../dashboard_2verificar_8php.html',1,'(Espacio de nombres global)']]],
  ['verify_25',['verify',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html#aa6f0d709ee797863db52b9e4626c7d55',1,'PHPMailer\PHPMailer\SMTP\verify($name)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html#aa6f0d709ee797863db52b9e4626c7d55',1,'PHPMailer\PHPMailer\SMTP\verify($name)']]],
  ['versión_20web_26',['Proyecto N.I.C.O.L.E Versión Web',['../index.html',1,'']]],
  ['version_27',['VERSION',['../class_f_p_d_f.html#a7345a5b3138619c768e9077cd399312d',1,'FPDF\VERSION'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a79ae6ea778fe4ad5fa5d6b1a1cebb26d',1,'PHPMailer\PHPMailer\PHPMailer\VERSION'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_o_p3.html#affdd38db9638306a2f7bc9f09b5f357e',1,'PHPMailer\PHPMailer\POP3\VERSION'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html#adb37dc6e8c061cbac377ab9ee88226e2',1,'PHPMailer\PHPMailer\SMTP\VERSION']]],
  ['version_202_20x_20x_28',['Patches to version 2.x.x',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md139',1,'']]],
  ['versions_29',['versions',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md48',1,'Legacy versions'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md147',1,'Legacy versions']]],
  ['via_20checkout_20pro_30',['🌟 Getting started with payment via Checkout Pro',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md132',1,'']]],
  ['via_20your_20own_20website_20forms_31',['🌟 Getting Started with payment via your own website forms',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md124',1,'']]],
  ['visual_20y_20técnico_32',['Endpoints N.I.C.O.L.E — Documento visual y técnico',['../endpoints.html',1,'']]]
];
