var searchData=
[
  ['background_0',['Background',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html#autotoc_md64',1,'Background'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html#autotoc_md163',1,'Background']]],
  ['backurls_1',['BackUrls',['../class_mercado_pago_1_1_resources_1_1_preference_1_1_back_urls.html',1,'MercadoPago::Resources::Preference']]],
  ['backurls_2ephp_2',['BackUrls.php',['../_back_urls_8php.html',1,'']]],
  ['bankinfo_3',['BankInfo',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info.html',1,'MercadoPago::Resources::Payment']]],
  ['bankinfo_2ephp_4',['BankInfo.php',['../_bank_info_8php.html',1,'']]],
  ['bankinfocollector_5',['BankInfoCollector',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_collector.html',1,'MercadoPago::Resources::Payment']]],
  ['bankinfocollector_2ephp_6',['BankInfoCollector.php',['../_bank_info_collector_8php.html',1,'']]],
  ['bankinfopayer_7',['BankInfoPayer',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_bank_info_payer.html',1,'MercadoPago::Resources::Payment']]],
  ['bankinfopayer_2ephp_8',['BankInfoPayer.php',['../_bank_info_payer_8php.html',1,'']]],
  ['barcode_9',['Barcode',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_barcode.html',1,'MercadoPago::Resources::Payment']]],
  ['barcode_2ephp_10',['Barcode.php',['../_barcode_8php.html',1,'']]],
  ['base_20de_20datos_11',['Consultar usuario en la base de datos',['../procesar__registro_8php.html#paso4',1,'']]],
  ['base64encodewrapmb_12',['base64EncodeWrapMB',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a4a424b86108eaafe1d8369db737cc47f',1,'PHPMailer\PHPMailer\PHPMailer\base64EncodeWrapMB($str, $linebreak=null)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a4a424b86108eaafe1d8369db737cc47f',1,'PHPMailer\PHPMailer\PHPMailer\base64EncodeWrapMB($str, $linebreak=null)']]],
  ['baseclient_13',['BaseClient',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_base_1_1_base_client.html',1,'MercadoPago::Tests::Client::Unit::Base']]],
  ['baseclient_2ephp_14',['BaseClient.php',['../_base_client_8php.html',1,'']]],
  ['basictable_15',['BasicTable',['../class_p_d_f.html#a29249473954e4420d6eabf4e278af3d0',1,'PDF']]],
  ['before_20proceeding_20to_20checkout_20pro_20page_16',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['beneficios_5fpremium_2ephp_17',['beneficios_premium.php',['../beneficios__premium_8php.html',1,'']]],
  ['billdata_18',['BillData',['../class_mercado_pago_1_1_resources_1_1_user_1_1_bill_data.html',1,'MercadoPago::Resources::User']]],
  ['billdata_2ephp_19',['BillData.php',['../_bill_data_8php.html',1,'']]],
  ['bin_20',['Bin',['../class_mercado_pago_1_1_resources_1_1_payment_method_1_1_bin.html',1,'MercadoPago::Resources::PaymentMethod']]],
  ['bin_2ephp_21',['Bin.php',['../_bin_8php.html',1,'']]],
  ['blank_22',['blank',['../class_dotenv_1_1_parser_1_1_value.html#a49f30a5eca89c9cb69ffb6615e8b1294',1,'Dotenv::Parser::Value']]],
  ['bootstrap_2ephp_23',['bootstrap.php',['../polyfill-ctype_2bootstrap_8php.html',1,'(Espacio de nombres global)'],['../polyfill-mbstring_2bootstrap_8php.html',1,'(Espacio de nombres global)'],['../polyfill-php80_2bootstrap_8php.html',1,'(Espacio de nombres global)']]],
  ['bootstrap80_2ephp_24',['bootstrap80.php',['../polyfill-ctype_2bootstrap80_8php.html',1,'(Espacio de nombres global)'],['../polyfill-mbstring_2bootstrap80_8php.html',1,'(Espacio de nombres global)']]],
  ['branching_20guidelines_25',['Branching Guidelines',['../md_vendor_2mercadopago_2dx-php_2_c_o_d_i_n_g___g_u_i_d_e_l_i_n_e_s.html#autotoc_md94',1,'']]],
  ['bug_20reports_26',['Bug Reports',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md100',1,'']]],
  ['build_27',['Build',['../class_t_t_f_parser.html#a633b58407236edc95997c8d4694eee51',1,'TTFParser']]],
  ['buildcmap_28',['BuildCmap',['../class_t_t_f_parser.html#ae415813333d9b1bc0cdf6ff0832f0cde',1,'TTFParser']]],
  ['buildfont_29',['BuildFont',['../class_t_t_f_parser.html#a66988913e7a001aa10d6999aa8bec9cc',1,'TTFParser']]],
  ['buildglyf_30',['BuildGlyf',['../class_t_t_f_parser.html#adc4cf2ee8eedddc538b866c75c244878',1,'TTFParser']]],
  ['buildhhea_31',['BuildHhea',['../class_t_t_f_parser.html#a7c6b39eb568510974148ab9b08db5fcc',1,'TTFParser']]],
  ['buildhmtx_32',['BuildHmtx',['../class_t_t_f_parser.html#a2f893e98aa99b4985d003988b8c7c3b8',1,'TTFParser']]],
  ['buildloca_33',['BuildLoca',['../class_t_t_f_parser.html#ab29a72cdb4974648fbb74c43369d4070',1,'TTFParser']]],
  ['buildmaxp_34',['BuildMaxp',['../class_t_t_f_parser.html#afc1504b822ad8fee8090e177100ca718',1,'TTFParser']]],
  ['buildpost_35',['BuildPost',['../class_t_t_f_parser.html#add276f04750d9c5abadf9c6f33b451db',1,'TTFParser']]],
  ['buyerreputation_36',['BuyerReputation',['../class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation.html',1,'MercadoPago::Resources::User']]],
  ['buyerreputation_2ephp_37',['BuyerReputation.php',['../_buyer_reputation_8php.html',1,'']]],
  ['buyerreputationcancelled_38',['BuyerReputationCancelled',['../class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_cancelled.html',1,'MercadoPago::Resources::User']]],
  ['buyerreputationcancelled_2ephp_39',['BuyerReputationCancelled.php',['../_buyer_reputation_cancelled_8php.html',1,'']]],
  ['buyerreputationnotyetrated_40',['BuyerReputationNotYetRated',['../class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_not_yet_rated.html',1,'MercadoPago::Resources::User']]],
  ['buyerreputationnotyetrated_2ephp_41',['BuyerReputationNotYetRated.php',['../_buyer_reputation_not_yet_rated_8php.html',1,'']]],
  ['buyerreputationtransactions_42',['BuyerReputationTransactions',['../class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_transactions.html',1,'MercadoPago::Resources::User']]],
  ['buyerreputationtransactions_2ephp_43',['BuyerReputationTransactions.php',['../_buyer_reputation_transactions_8php.html',1,'']]],
  ['buyerreputationunrated_44',['BuyerReputationUnrated',['../class_mercado_pago_1_1_resources_1_1_user_1_1_buyer_reputation_unrated.html',1,'MercadoPago::Resources::User']]],
  ['buyerreputationunrated_2ephp_45',['BuyerReputationUnrated.php',['../_buyer_reputation_unrated_8php.html',1,'']]],
  ['by_20step_20migration_46',['Step-by-Step Migration',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md109',1,'']]]
];
