var searchData=
[
  ['páginas_20informativas_0',['Páginas informativas',['../index.html#autotoc_md76',1,'']]],
  ['page_1',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['pageno_2',['PageNo',['../class_f_p_d_f.html#af97a0239f79f597b5c88cc68b385f7af',1,'FPDF']]],
  ['paging_3',['Paging',['../class_mercado_pago_1_1_resources_1_1_common_1_1_paging.html',1,'MercadoPago::Resources::Common']]],
  ['paging_2ephp_4',['Paging.php',['../_paging_8php.html',1,'']]],
  ['pago_5',['Pagos con Mercado Pago',['../index.html#autotoc_md83',1,'']]],
  ['pago_20docs_6',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['pago_20php_20sdk_7',['Contributing to the Mercado Pago PHP SDK',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['pago_20sdk_20for_20php_8',['Mercado Pago SDK for PHP',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md120',1,'']]],
  ['pago_2ephp_9',['pago.php',['../pago_8php.html',1,'']]],
  ['pago_5fexitoso_2ephp_10',['pago_exitoso.php',['../pago__exitoso_8php.html',1,'']]],
  ['pago_5ffallido_2ephp_11',['pago_fallido.php',['../pago__fallido_8php.html',1,'']]],
  ['pago_5fpendiente_2ephp_12',['pago_pendiente.php',['../pago__pendiente_8php.html',1,'']]],
  ['pagos_20con_20mercado_20pago_13',['Pagos con Mercado Pago',['../index.html#autotoc_md83',1,'']]],
  ['parse_14',['Parse',['../class_t_t_f_parser.html#a67edb1bd7297f06b04dcbc8b6135a5db',1,'TTFParser']]],
  ['parse_15',['parse',['../class_dotenv_1_1_dotenv.html#ada8a0cbce967b8057e01705f211ba59d',1,'Dotenv\Dotenv\parse()'],['../class_dotenv_1_1_parser_1_1_parser.html#a5fc1e6892cb2bdca71ad1fdc19b95e89',1,'Dotenv\Parser\Parser\parse()'],['../interface_dotenv_1_1_parser_1_1_parser_interface.html#a610d34ef55e2f248366ae56901952c5e',1,'Dotenv\Parser\ParserInterface\parse()']]],
  ['parseaddresses_16',['parseAddresses',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#afc87a09c663eb29b6fb73c7fa6163116',1,'PHPMailer\PHPMailer\PHPMailer\parseAddresses($addrstr, $useimap=null, $charset=self::CHARSET_ISO88591)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#abad0b575eddce5def4c8775f3c81425d',1,'PHPMailer\PHPMailer\PHPMailer\parseAddresses($addrstr, $useimap=true, $charset=self::CHARSET_ISO88591)']]],
  ['parsecmap_17',['ParseCmap',['../class_t_t_f_parser.html#af35ff7a233c6de7751e4df1ead414315',1,'TTFParser']]],
  ['parseglyf_18',['ParseGlyf',['../class_t_t_f_parser.html#ade723de9cd8c9b8ca0dacd4dabc3bd33',1,'TTFParser']]],
  ['parsehead_19',['ParseHead',['../class_t_t_f_parser.html#ae87aa2ef8fef27cff059106d57d1303c',1,'TTFParser']]],
  ['parsehellofields_20',['parseHelloFields',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html#a1e37ec8121884138d43b236545a07ef6',1,'PHPMailer\PHPMailer\SMTP\parseHelloFields($type)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_s_m_t_p.html#a1e37ec8121884138d43b236545a07ef6',1,'PHPMailer\PHPMailer\SMTP\parseHelloFields($type)']]],
  ['parsehhea_21',['ParseHhea',['../class_t_t_f_parser.html#a5068ab1775e58f2ddf8a5c2a74e11c43',1,'TTFParser']]],
  ['parsehmtx_22',['ParseHmtx',['../class_t_t_f_parser.html#adb82cd858d9cbab2cf350202662a8959',1,'TTFParser']]],
  ['parseloca_23',['ParseLoca',['../class_t_t_f_parser.html#a9556b5853c5e9e07f860fd63a31b34f5',1,'TTFParser']]],
  ['parsemaxp_24',['ParseMaxp',['../class_t_t_f_parser.html#a45ca897180839588639c1c6a1fcaaf8b',1,'TTFParser']]],
  ['parsename_25',['ParseName',['../class_t_t_f_parser.html#a1bf8839b790543a35722529d151cd0df',1,'TTFParser']]],
  ['parseoffsettable_26',['ParseOffsetTable',['../class_t_t_f_parser.html#a2a0c425d7064410ff2a476920d49134a',1,'TTFParser']]],
  ['parseos2_27',['ParseOS2',['../class_t_t_f_parser.html#aeeb7b994865c9690f4c5e7877c89e0a6',1,'TTFParser']]],
  ['parsepost_28',['ParsePost',['../class_t_t_f_parser.html#aecfdf351bb047a3c72cbc9db0ae75e46',1,'TTFParser']]],
  ['parser_29',['Parser',['../class_dotenv_1_1_parser_1_1_parser.html',1,'Dotenv::Parser']]],
  ['parser_2ephp_30',['Parser.php',['../_parser_8php.html',1,'']]],
  ['parserinterface_31',['ParserInterface',['../interface_dotenv_1_1_parser_1_1_parser_interface.html',1,'Dotenv::Parser']]],
  ['parserinterface_2ephp_32',['ParserInterface.php',['../_parser_interface_8php.html',1,'']]],
  ['parsesimpleraddresses_33',['parseSimplerAddresses',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a48778263da11fd30349a33f100cd1674',1,'PHPMailer::PHPMailer::PHPMailer']]],
  ['parseurl_34',['parseUrl',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_d_s_n_configurator.html#a58058b9cb36ff5590bc730b0742367de',1,'PHPMailer\PHPMailer\DSNConfigurator\parseUrl($url)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_d_s_n_configurator.html#a58058b9cb36ff5590bc730b0742367de',1,'PHPMailer\PHPMailer\DSNConfigurator\parseUrl($url)']]],
  ['patch_35',['PATCH',['../class_mercado_pago_1_1_net_1_1_http_method.html#a3b57774618e68b76c2e4e1ae8a7e396f',1,'MercadoPago::Net::HttpMethod']]],
  ['patches_20to_20version_202_20x_20x_36',['Patches to version 2.x.x',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md139',1,'']]],
  ['paths_37',['Paths',['../class_dotenv_1_1_store_1_1_file_1_1_paths.html',1,'Dotenv::Store::File']]],
  ['paths_2ephp_38',['Paths.php',['../_paths_8php.html',1,'']]],
  ['payer_39',['Payer',['../class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_payer.html',1,'MercadoPago\Resources\MerchantOrder\Payer'],['../class_mercado_pago_1_1_resources_1_1_order_1_1_payer.html',1,'MercadoPago\Resources\Order\Payer'],['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payer.html',1,'MercadoPago\Resources\Payment\Payer'],['../class_mercado_pago_1_1_resources_1_1_preference_1_1_payer.html',1,'MercadoPago\Resources\Preference\Payer']]],
  ['payer_2ephp_40',['Payer.php',['../_merchant_order_2_payer_8php.html',1,'(Espacio de nombres global)'],['../_order_2_payer_8php.html',1,'(Espacio de nombres global)'],['../_payment_2_payer_8php.html',1,'(Espacio de nombres global)'],['../_preference_2_payer_8php.html',1,'(Espacio de nombres global)']]],
  ['payment_41',['Payment',['../class_mercado_pago_1_1_resources_1_1_invoice_1_1_payment.html',1,'MercadoPago\Resources\Invoice\Payment'],['../class_mercado_pago_1_1_resources_1_1_merchant_order_1_1_payment.html',1,'MercadoPago\Resources\MerchantOrder\Payment'],['../class_mercado_pago_1_1_resources_1_1_order_1_1_payment.html',1,'MercadoPago\Resources\Order\Payment'],['../class_mercado_pago_1_1_resources_1_1_payment.html',1,'MercadoPago\Resources\Payment']]],
  ['payment_20via_20checkout_20pro_42',['🌟 Getting started with payment via Checkout Pro',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md132',1,'']]],
  ['payment_20via_20your_20own_20website_20forms_43',['🌟 Getting Started with payment via your own website forms',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md124',1,'']]],
  ['payment_2ephp_44',['Payment.php',['../_invoice_2_payment_8php.html',1,'(Espacio de nombres global)'],['../_merchant_order_2_payment_8php.html',1,'(Espacio de nombres global)'],['../_order_2_payment_8php.html',1,'(Espacio de nombres global)'],['../_payment_8php.html',1,'(Espacio de nombres global)']]],
  ['paymentcancelrequest_45',['PaymentCancelRequest',['../class_mercado_pago_1_1_client_1_1_payment_1_1_payment_cancel_request.html',1,'MercadoPago::Client::Payment']]],
  ['paymentcancelrequest_2ephp_46',['PaymentCancelRequest.php',['../_payment_cancel_request_8php.html',1,'']]],
  ['paymentcapturerequest_47',['PaymentCaptureRequest',['../class_mercado_pago_1_1_client_1_1_payment_1_1_payment_capture_request.html',1,'MercadoPago::Client::Payment']]],
  ['paymentcapturerequest_2ephp_48',['PaymentCaptureRequest.php',['../_payment_capture_request_8php.html',1,'']]],
  ['paymentclient_49',['PaymentClient',['../class_mercado_pago_1_1_client_1_1_payment_1_1_payment_client.html',1,'MercadoPago::Client::Payment']]],
  ['paymentclient_2ephp_50',['PaymentClient.php',['../_payment_client_8php.html',1,'']]],
  ['paymentclientittest_51',['PaymentClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_1_1_payment_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Payment']]],
  ['paymentclientittest_2ephp_52',['PaymentClientITTest.php',['../_payment_client_i_t_test_8php.html',1,'']]],
  ['paymentclientunittest_53',['PaymentClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_1_1_payment_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Payment']]],
  ['paymentclientunittest_2ephp_54',['PaymentClientUnitTest.php',['../_payment_client_unit_test_8php.html',1,'']]],
  ['paymentdiscounts_55',['PaymentDiscounts',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_discounts.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentdiscounts_2ephp_56',['PaymentDiscounts.php',['../_payment_discounts_8php.html',1,'']]],
  ['paymentfee_57',['PaymentFee',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_fee.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentfee_2ephp_58',['PaymentFee.php',['../_payment_fee_8php.html',1,'']]],
  ['paymentintent_59',['PaymentIntent',['../class_mercado_pago_1_1_resources_1_1_payment_intent.html',1,'MercadoPago::Resources']]],
  ['paymentintent_2ephp_60',['PaymentIntent.php',['../_payment_intent_8php.html',1,'']]],
  ['paymentintentadditionalinfo_61',['PaymentIntentAdditionalInfo',['../class_mercado_pago_1_1_resources_1_1_point_1_1_payment_intent_additional_info.html',1,'MercadoPago::Resources::Point']]],
  ['paymentintentadditionalinfo_2ephp_62',['PaymentIntentAdditionalInfo.php',['../_payment_intent_additional_info_8php.html',1,'']]],
  ['paymentintentcancel_63',['PaymentIntentCancel',['../class_mercado_pago_1_1_resources_1_1_payment_intent_cancel.html',1,'MercadoPago::Resources']]],
  ['paymentintentcancel_2ephp_64',['PaymentIntentCancel.php',['../_payment_intent_cancel_8php.html',1,'']]],
  ['paymentintentlist_65',['PaymentIntentList',['../class_mercado_pago_1_1_resources_1_1_payment_intent_list.html',1,'MercadoPago::Resources']]],
  ['paymentintentlist_2ephp_66',['PaymentIntentList.php',['../_payment_intent_list_8php.html',1,'']]],
  ['paymentintentpayment_67',['PaymentIntentPayment',['../class_mercado_pago_1_1_resources_1_1_point_1_1_payment_intent_payment.html',1,'MercadoPago::Resources::Point']]],
  ['paymentintentpayment_2ephp_68',['PaymentIntentPayment.php',['../_payment_intent_payment_8php.html',1,'']]],
  ['paymentintentstatus_69',['PaymentIntentStatus',['../class_mercado_pago_1_1_resources_1_1_payment_intent_status.html',1,'MercadoPago::Resources']]],
  ['paymentintentstatus_2ephp_70',['PaymentIntentStatus.php',['../_payment_intent_status_8php.html',1,'']]],
  ['paymentmethod_71',['PaymentMethod',['../class_mercado_pago_1_1_resources_1_1_customer_1_1_payment_method.html',1,'MercadoPago\Resources\Customer\PaymentMethod'],['../class_mercado_pago_1_1_resources_1_1_order_1_1_payment_method.html',1,'MercadoPago\Resources\Order\PaymentMethod'],['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method.html',1,'MercadoPago\Resources\Payment\PaymentMethod'],['../class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_method.html',1,'MercadoPago\Resources\Preference\PaymentMethod']]],
  ['paymentmethod_2ephp_72',['PaymentMethod.php',['../_customer_2_payment_method_8php.html',1,'(Espacio de nombres global)'],['../_order_2_payment_method_8php.html',1,'(Espacio de nombres global)'],['../_payment_2_payment_method_8php.html',1,'(Espacio de nombres global)'],['../_preference_2_payment_method_8php.html',1,'(Espacio de nombres global)']]],
  ['paymentmethodclient_73',['PaymentMethodClient',['../class_mercado_pago_1_1_client_1_1_payment_method_1_1_payment_method_client.html',1,'MercadoPago::Client::PaymentMethod']]],
  ['paymentmethodclient_2ephp_74',['PaymentMethodClient.php',['../_payment_method_client_8php.html',1,'']]],
  ['paymentmethodclientittest_75',['PaymentMethodClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_method_1_1_payment_method_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::PaymentMethod']]],
  ['paymentmethodclientittest_2ephp_76',['PaymentMethodClientITTest.php',['../_payment_method_client_i_t_test_8php.html',1,'']]],
  ['paymentmethodclientunittest_77',['PaymentMethodClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_method_1_1_payment_method_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::PaymentMethod']]],
  ['paymentmethodclientunittest_2ephp_78',['PaymentMethodClientUnitTest.php',['../_payment_method_client_unit_test_8php.html',1,'']]],
  ['paymentmethodconfig_79',['PaymentMethodConfig',['../class_mercado_pago_1_1_resources_1_1_order_1_1_payment_method_config.html',1,'MercadoPago::Resources::Order']]],
  ['paymentmethodconfig_2ephp_80',['PaymentMethodConfig.php',['../_payment_method_config_8php.html',1,'']]],
  ['paymentmethoddata_81',['PaymentMethodData',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_data.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentmethoddata_2ephp_82',['PaymentMethodData.php',['../_payment_method_data_8php.html',1,'']]],
  ['paymentmethodlistresult_83',['PaymentMethodListResult',['../class_mercado_pago_1_1_resources_1_1_payment_method_1_1_payment_method_list_result.html',1,'MercadoPago::Resources::PaymentMethod']]],
  ['paymentmethodlistresult_2ephp_84',['PaymentMethodListResult.php',['../_payment_method_list_result_8php.html',1,'']]],
  ['paymentmethodresult_85',['PaymentMethodResult',['../class_mercado_pago_1_1_resources_1_1_payment_method_result.html',1,'MercadoPago::Resources']]],
  ['paymentmethodresult_2ephp_86',['PaymentMethodResult.php',['../_payment_method_result_8php.html',1,'']]],
  ['paymentmethodrules_87',['PaymentMethodRules',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_method_rules.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentmethodrules_2ephp_88',['PaymentMethodRules.php',['../_payment_method_rules_8php.html',1,'']]],
  ['paymentmethods_89',['PaymentMethods',['../class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_methods.html',1,'MercadoPago::Resources::Preference']]],
  ['paymentmethods_2ephp_90',['PaymentMethods.php',['../_payment_methods_8php.html',1,'']]],
  ['paymentmethodsallowed_91',['PaymentMethodsAllowed',['../class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_payment_methods_allowed.html',1,'MercadoPago::Resources::PreApprovalPlan']]],
  ['paymentmethodsallowed_2ephp_92',['PaymentMethodsAllowed.php',['../_payment_methods_allowed_8php.html',1,'']]],
  ['paymentrefund_93',['PaymentRefund',['../class_mercado_pago_1_1_resources_1_1_payment_refund.html',1,'MercadoPago::Resources']]],
  ['paymentrefund_2ephp_94',['PaymentRefund.php',['../_payment_refund_8php.html',1,'']]],
  ['paymentrefundclient_95',['PaymentRefundClient',['../class_mercado_pago_1_1_client_1_1_payment_1_1_payment_refund_client.html',1,'MercadoPago::Client::Payment']]],
  ['paymentrefundclient_2ephp_96',['PaymentRefundClient.php',['../_payment_refund_client_8php.html',1,'']]],
  ['paymentrefundclientittest_97',['PaymentRefundClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_payment_1_1_payment_refund_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Payment']]],
  ['paymentrefundclientittest_2ephp_98',['PaymentRefundClientITTest.php',['../_payment_refund_client_i_t_test_8php.html',1,'']]],
  ['paymentrefundclientunittest_99',['PaymentRefundClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_payment_1_1_payment_refund_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Payment']]],
  ['paymentrefundclientunittest_2ephp_100',['PaymentRefundClientUnitTest.php',['../_payment_refund_client_unit_test_8php.html',1,'']]],
  ['paymentrefundcreaterequest_101',['PaymentRefundCreateRequest',['../class_mercado_pago_1_1_client_1_1_payment_1_1_payment_refund_create_request.html',1,'MercadoPago::Client::Payment']]],
  ['paymentrefundcreaterequest_2ephp_102',['PaymentRefundCreateRequest.php',['../_payment_refund_create_request_8php.html',1,'']]],
  ['paymentrefundlistresult_103',['PaymentRefundListResult',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_refund_list_result.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentrefundlistresult_2ephp_104',['PaymentRefundListResult.php',['../_payment_refund_list_result_8php.html',1,'']]],
  ['paymentrefundresult_105',['PaymentRefundResult',['../class_mercado_pago_1_1_resources_1_1_payment_refund_result.html',1,'MercadoPago::Resources']]],
  ['paymentrefundresult_2ephp_106',['PaymentRefundResult.php',['../_payment_refund_result_8php.html',1,'']]],
  ['paymentsearch_107',['PaymentSearch',['../class_mercado_pago_1_1_resources_1_1_payment_search.html',1,'MercadoPago::Resources']]],
  ['paymentsearch_2ephp_108',['PaymentSearch.php',['../_payment_search_8php.html',1,'']]],
  ['paymentsearchresult_109',['PaymentSearchResult',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_payment_search_result.html',1,'MercadoPago::Resources::Payment']]],
  ['paymentsearchresult_2ephp_110',['PaymentSearchResult.php',['../_payment_search_result_8php.html',1,'']]],
  ['paymenttype_111',['PaymentType',['../class_mercado_pago_1_1_resources_1_1_preference_1_1_payment_type.html',1,'MercadoPago::Resources::Preference']]],
  ['paymenttype_2ephp_112',['PaymentType.php',['../_payment_type_8php.html',1,'']]],
  ['pdf_113',['PDF',['../class_p_d_f.html',1,'']]],
  ['phone_114',['Phone',['../class_mercado_pago_1_1_resources_1_1_common_1_1_phone.html',1,'MercadoPago\Resources\Common\Phone'],['../class_mercado_pago_1_1_resources_1_1_user_1_1_phone.html',1,'MercadoPago\Resources\User\Phone']]],
  ['phone_2ephp_115',['Phone.php',['../_common_2_phone_8php.html',1,'(Espacio de nombres global)'],['../_user_2_phone_8php.html',1,'(Espacio de nombres global)']]],
  ['php_116',['PHP',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md120',1,'Mercado Pago SDK for PHP'],['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md43',1,'PHPMailer – A full-featured email creation and transfer class for PHP'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md142',1,'PHPMailer – A full-featured email creation and transfer class for PHP']]],
  ['php_117',['php',['../endpoints.html#actualizar',1,'Actualizar Usuario (actualizar_usuario.php)'],['../procesar__registro_8php.html#paso2',1,'Capturar datos del formulario login.php'],['../endpoints.html#login',1,'Inicio de Sesión (login.php)'],['../endpoints.html#obtener',1,'Obtener Usuario (obtener_usuario.php)'],['../endpoints.html#preferencias',1,'Preferencias del Usuario (guardar_preferencia.php)'],['../endpoints.html#reenviar',1,'Reenviar Código de Verificación (reenviar_codigo.php)'],['../endpoints.html#registro',1,'Registro de Usuario (register.php)'],['../endpoints.html#verificar',1,'Verificar Código (verificar.php)'],['../endpoints.html#webhook',1,'Webhook de MercadoPago (dashboard/webhook.php)']]],
  ['php_20sdk_118',['Contributing to the Mercado Pago PHP SDK',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['php_20sdk_20v2_20to_20v3_119',['Migration Guide from MercadoPago PHP SDK v2 to v3',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['php80_120',['Php80',['../class_symfony_1_1_polyfill_1_1_php80_1_1_php80.html',1,'Symfony::Polyfill::Php80']]],
  ['php80_2ephp_121',['Php80.php',['../_php80_8php.html',1,'']]],
  ['phpmailer_122',['PHPMailer',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html',1,'PHPMailer\PHPMailer\PHPMailer'],['../namespace_p_h_p_mailer.html',1,'PHPMailer'],['../md_libs_2_p_h_p_mailer_2_s_e_c_u_r_i_t_y.html',1,'Security notices relating to PHPMailer'],['../md_vendor_2phpmailer_2phpmailer_2_s_e_c_u_r_i_t_y.html',1,'Security notices relating to PHPMailer'],['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html#autotoc_md66',1,'SMTPUTF8 in PHPMailer'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html#autotoc_md165',1,'SMTPUTF8 in PHPMailer']]],
  ['phpmailer_20–_20a_20full_20featured_20email_20creation_20and_20transfer_20class_20for_20php_123',['PHPMailer – A full featured email creation and transfer class for PHP',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md43',1,'PHPMailer – A full-featured email creation and transfer class for PHP'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md142',1,'PHPMailer – A full-featured email creation and transfer class for PHP']]],
  ['phpmailer_20for_20enterprise_124',['PHPMailer For Enterprise',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md58',1,'PHPMailer For Enterprise'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md157',1,'PHPMailer For Enterprise']]],
  ['phpmailer_2elang_2daf_2ephp_125',['phpmailer.lang-af.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-af_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-af_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dar_2ephp_126',['phpmailer.lang-ar.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ar_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ar_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2das_2ephp_127',['phpmailer.lang-as.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-as_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-as_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2daz_2ephp_128',['phpmailer.lang-az.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-az_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-az_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dba_2ephp_129',['phpmailer.lang-ba.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ba_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ba_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dbe_2ephp_130',['phpmailer.lang-be.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-be_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-be_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dbg_2ephp_131',['phpmailer.lang-bg.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-bg_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-bg_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dbn_2ephp_132',['phpmailer.lang-bn.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-bn_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-bn_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dca_2ephp_133',['phpmailer.lang-ca.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ca_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ca_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dcs_2ephp_134',['phpmailer.lang-cs.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-cs_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-cs_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dda_2ephp_135',['phpmailer.lang-da.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-da_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-da_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dde_2ephp_136',['phpmailer.lang-de.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-de_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-de_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2del_2ephp_137',['phpmailer.lang-el.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-el_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-el_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2deo_2ephp_138',['phpmailer.lang-eo.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-eo_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-eo_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2des_2ephp_139',['phpmailer.lang-es.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-es_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-es_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2det_2ephp_140',['phpmailer.lang-et.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-et_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-et_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dfa_2ephp_141',['phpmailer.lang-fa.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-fa_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-fa_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dfi_2ephp_142',['phpmailer.lang-fi.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-fi_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-fi_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dfo_2ephp_143',['phpmailer.lang-fo.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-fo_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-fo_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dfr_2ephp_144',['phpmailer.lang-fr.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-fr_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-fr_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dgl_2ephp_145',['phpmailer.lang-gl.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-gl_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-gl_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dhe_2ephp_146',['phpmailer.lang-he.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-he_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-he_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dhi_2ephp_147',['phpmailer.lang-hi.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-hi_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-hi_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dhr_2ephp_148',['phpmailer.lang-hr.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-hr_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-hr_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dhu_2ephp_149',['phpmailer.lang-hu.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-hu_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-hu_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dhy_2ephp_150',['phpmailer.lang-hy.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-hy_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-hy_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2did_2ephp_151',['phpmailer.lang-id.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-id_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-id_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dit_2ephp_152',['phpmailer.lang-it.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-it_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-it_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dja_2ephp_153',['phpmailer.lang-ja.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ja_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ja_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dka_2ephp_154',['phpmailer.lang-ka.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ka_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ka_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dko_2ephp_155',['phpmailer.lang-ko.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ko_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ko_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dku_2ephp_156',['phpmailer.lang-ku.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ku_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ku_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dlt_2ephp_157',['phpmailer.lang-lt.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-lt_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-lt_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dlv_2ephp_158',['phpmailer.lang-lv.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-lv_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-lv_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dmg_2ephp_159',['phpmailer.lang-mg.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-mg_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-mg_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dmn_2ephp_160',['phpmailer.lang-mn.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-mn_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-mn_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dms_2ephp_161',['phpmailer.lang-ms.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ms_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ms_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dnb_2ephp_162',['phpmailer.lang-nb.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-nb_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-nb_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dnl_2ephp_163',['phpmailer.lang-nl.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-nl_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-nl_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dpl_2ephp_164',['phpmailer.lang-pl.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-pl_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-pl_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dpt_2ephp_165',['phpmailer.lang-pt.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-pt_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-pt_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dpt_5fbr_2ephp_166',['phpmailer.lang-pt_br.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-pt__br_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-pt__br_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dro_2ephp_167',['phpmailer.lang-ro.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ro_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ro_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dru_2ephp_168',['phpmailer.lang-ru.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ru_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ru_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsi_2ephp_169',['phpmailer.lang-si.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-si_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-si_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsk_2ephp_170',['phpmailer.lang-sk.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-sk_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-sk_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsl_2ephp_171',['phpmailer.lang-sl.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-sl_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-sl_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsr_2ephp_172',['phpmailer.lang-sr.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-sr_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-sr_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsr_5flatn_2ephp_173',['phpmailer.lang-sr_latn.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-sr__latn_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-sr__latn_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dsv_2ephp_174',['phpmailer.lang-sv.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-sv_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-sv_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dtl_2ephp_175',['phpmailer.lang-tl.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-tl_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-tl_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dtr_2ephp_176',['phpmailer.lang-tr.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-tr_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-tr_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2duk_2ephp_177',['phpmailer.lang-uk.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-uk_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-uk_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dur_2ephp_178',['phpmailer.lang-ur.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-ur_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-ur_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dvi_2ephp_179',['phpmailer.lang-vi.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-vi_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-vi_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dzh_2ephp_180',['phpmailer.lang-zh.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-zh_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-zh_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2elang_2dzh_5fcn_2ephp_181',['phpmailer.lang-zh_cn.php',['../libs_2_p_h_p_mailer_2language_2phpmailer_8lang-zh__cn_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2language_2phpmailer_8lang-zh__cn_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_2ephp_182',['PHPMailer.php',['../libs_2_p_h_p_mailer_2src_2_p_h_p_mailer_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2src_2_p_h_p_mailer_8php.html',1,'(Espacio de nombres global)']]],
  ['phpmailer_3a_3aphpmailer_183',['PHPMailer',['../namespace_p_h_p_mailer_1_1_p_h_p_mailer.html',1,'PHPMailer']]],
  ['phpoption_184',['PhpOption',['../namespace_php_option.html',1,'']]],
  ['phptoken_185',['PhpToken',['../class_symfony_1_1_polyfill_1_1_php80_1_1_php_token.html',1,'Symfony::Polyfill::Php80']]],
  ['phptoken_2ephp_186',['PhpToken.php',['../_php_token_8php.html',1,'(Espacio de nombres global)'],['../_resources_2stubs_2_php_token_8php.html',1,'(Espacio de nombres global)']]],
  ['ping_5fdb_187',['ping_db',['../namespacemain.html#a43ab2d8f0fc7f809b65f51b1cfa4bab2',1,'main']]],
  ['platform_5fcheck_2ephp_188',['platform_check.php',['../platform__check_8php.html',1,'']]],
  ['pointclient_189',['PointClient',['../class_mercado_pago_1_1_client_1_1_point_1_1_point_client.html',1,'MercadoPago::Client::Point']]],
  ['pointclient_2ephp_190',['PointClient.php',['../_point_client_8php.html',1,'']]],
  ['pointclientittest_191',['PointClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_point_1_1_point_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Point']]],
  ['pointclientittest_2ephp_192',['PointClientITTest.php',['../_point_client_i_t_test_8php.html',1,'']]],
  ['pointclientunittest_193',['PointClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_point_1_1_point_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Point']]],
  ['pointclientunittest_2ephp_194',['PointClientUnitTest.php',['../_point_client_unit_test_8php.html',1,'']]],
  ['pointdeviceoperatingmode_195',['PointDeviceOperatingMode',['../class_mercado_pago_1_1_resources_1_1_point_device_operating_mode.html',1,'MercadoPago::Resources']]],
  ['pointdeviceoperatingmode_2ephp_196',['PointDeviceOperatingMode.php',['../_point_device_operating_mode_8php.html',1,'']]],
  ['pointdeviceoperatingmoderequest_197',['PointDeviceOperatingModeRequest',['../class_mercado_pago_1_1_client_1_1_point_1_1_point_device_operating_mode_request.html',1,'MercadoPago::Client::Point']]],
  ['pointdeviceoperatingmoderequest_2ephp_198',['PointDeviceOperatingModeRequest.php',['../_point_device_operating_mode_request_8php.html',1,'']]],
  ['pointdevices_199',['PointDevices',['../class_mercado_pago_1_1_resources_1_1_point_devices.html',1,'MercadoPago::Resources']]],
  ['pointdevices_2ephp_200',['PointDevices.php',['../_point_devices_8php.html',1,'']]],
  ['pointofinteraction_201',['PointOfInteraction',['../class_mercado_pago_1_1_resources_1_1_payment_1_1_point_of_interaction.html',1,'MercadoPago::Resources::Payment']]],
  ['pointofinteraction_2ephp_202',['PointOfInteraction.php',['../_point_of_interaction_8php.html',1,'']]],
  ['pointpaymentintentlistrequest_203',['PointPaymentIntentListRequest',['../class_mercado_pago_1_1_client_1_1_point_1_1_point_payment_intent_list_request.html',1,'MercadoPago::Client::Point']]],
  ['pointpaymentintentlistrequest_2ephp_204',['PointPaymentIntentListRequest.php',['../_point_payment_intent_list_request_8php.html',1,'']]],
  ['pop3_205',['POP3',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_o_p3.html',1,'PHPMailer::PHPMailer']]],
  ['pop3_2ephp_206',['POP3.php',['../libs_2_p_h_p_mailer_2src_2_p_o_p3_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2src_2_p_o_p3_8php.html',1,'(Espacio de nombres global)']]],
  ['popbeforesmtp_207',['popBeforeSmtp',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_o_p3.html#a19640d96aebdde899ccd721ab1299392',1,'PHPMailer\PHPMailer\POP3\popBeforeSmtp( $host, $port=false, $timeout=false, $username=&apos;&apos;, $password=&apos;&apos;, $debug_level=0)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_o_p3.html#a19640d96aebdde899ccd721ab1299392',1,'PHPMailer\PHPMailer\POP3\popBeforeSmtp( $host, $port=false, $timeout=false, $username=&apos;&apos;, $password=&apos;&apos;, $debug_level=0)']]],
  ['post_208',['POST',['../class_mercado_pago_1_1_net_1_1_http_method.html#ac8535d0171f2c12d7b61a65acc87cff2',1,'MercadoPago\Net\HttpMethod\POST'],['../procesar__registro_8php.html#paso10',1,'Redirección si no es POST'],['../procesar__registro_8php.html#paso7',1,'Redirigir si no es POST'],['../procesar__registro_8php.html#paso1',1,'Verificar método POST']]],
  ['postfix_20gotcha_209',['Postfix gotcha',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html#autotoc_md67',1,'Postfix gotcha'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html#autotoc_md166',1,'Postfix gotcha']]],
  ['postsend_210',['postSend',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#ae060a001c53211f8e48c6e200174e6a1',1,'PHPMailer\PHPMailer\PHPMailer\postSend()'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#ae060a001c53211f8e48c6e200174e6a1',1,'PHPMailer\PHPMailer\PHPMailer\postSend()']]],
  ['pr_20validation_20checklist_3a_211',['PR validation checklist:',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html#autotoc_md119',1,'']]],
  ['preapproval_212',['PreApproval',['../class_mercado_pago_1_1_resources_1_1_pre_approval.html',1,'MercadoPago::Resources']]],
  ['preapproval_2ephp_213',['PreApproval.php',['../_pre_approval_8php.html',1,'']]],
  ['preapprovalclient_214',['PreApprovalClient',['../class_mercado_pago_1_1_client_1_1_pre_approval_1_1_pre_approval_client.html',1,'MercadoPago::Client::PreApproval']]],
  ['preapprovalclient_2ephp_215',['PreApprovalClient.php',['../_pre_approval_client_8php.html',1,'']]],
  ['preapprovalclientittest_216',['PreApprovalClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_1_1_pre_approval_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::PreApproval']]],
  ['preapprovalclientittest_2ephp_217',['PreApprovalClientITTest.php',['../_pre_approval_client_i_t_test_8php.html',1,'']]],
  ['preapprovalclientunittest_218',['PreApprovalClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_pre_approval_1_1_pre_approval_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::PreApproval']]],
  ['preapprovalclientunittest_2ephp_219',['PreApprovalClientUnitTest.php',['../_pre_approval_client_unit_test_8php.html',1,'']]],
  ['preapprovallistresult_220',['PreApprovalListResult',['../class_mercado_pago_1_1_resources_1_1_pre_approval_1_1_pre_approval_list_result.html',1,'MercadoPago::Resources::PreApproval']]],
  ['preapprovallistresult_2ephp_221',['PreApprovalListResult.php',['../_pre_approval_list_result_8php.html',1,'']]],
  ['preapprovalplan_222',['PreApprovalPlan',['../class_mercado_pago_1_1_resources_1_1_pre_approval_plan.html',1,'MercadoPago::Resources']]],
  ['preapprovalplan_2ephp_223',['PreApprovalPlan.php',['../_pre_approval_plan_8php.html',1,'']]],
  ['preapprovalplanclient_224',['PreApprovalPlanClient',['../class_mercado_pago_1_1_client_1_1_pre_approval_plan_1_1_pre_approval_plan_client.html',1,'MercadoPago::Client::PreApprovalPlan']]],
  ['preapprovalplanclient_2ephp_225',['PreApprovalPlanClient.php',['../_pre_approval_plan_client_8php.html',1,'']]],
  ['preapprovalplanclientittest_226',['PreApprovalPlanClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_pre_approval_plan_1_1_pre_approval_plan_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::PreApprovalPlan']]],
  ['preapprovalplanclientittest_2ephp_227',['PreApprovalPlanClientITTest.php',['../_pre_approval_plan_client_i_t_test_8php.html',1,'']]],
  ['preapprovalplanclientunittest_228',['PreApprovalPlanClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_pre_approval_plan_1_1_pre_approval_plan_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::PreApprovalPlan']]],
  ['preapprovalplanclientunittest_2ephp_229',['PreApprovalPlanClientUnitTest.php',['../_pre_approval_plan_client_unit_test_8php.html',1,'']]],
  ['preapprovalplanlistresult_230',['PreApprovalPlanListResult',['../class_mercado_pago_1_1_resources_1_1_pre_approval_plan_1_1_pre_approval_plan_list_result.html',1,'MercadoPago::Resources::PreApprovalPlan']]],
  ['preapprovalplanlistresult_2ephp_231',['PreApprovalPlanListResult.php',['../_pre_approval_plan_list_result_8php.html',1,'']]],
  ['preapprovalplansearch_232',['PreApprovalPlanSearch',['../class_mercado_pago_1_1_resources_1_1_pre_approval_plan_search.html',1,'MercadoPago::Resources']]],
  ['preapprovalplansearch_2ephp_233',['PreApprovalPlanSearch.php',['../_pre_approval_plan_search_8php.html',1,'']]],
  ['preapprovalsearch_234',['PreApprovalSearch',['../class_mercado_pago_1_1_resources_1_1_pre_approval_search.html',1,'MercadoPago::Resources']]],
  ['preapprovalsearch_2ephp_235',['PreApprovalSearch.php',['../_pre_approval_search_8php.html',1,'']]],
  ['preference_236',['Preference',['../class_mercado_pago_1_1_resources_1_1_preference.html',1,'MercadoPago::Resources']]],
  ['preference_20before_20proceeding_20to_20checkout_20pro_20page_237',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['preference_20on_20mercado_20pago_20docs_238',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['preference_2ephp_239',['Preference.php',['../_preference_8php.html',1,'']]],
  ['preferenceclient_240',['PreferenceClient',['../class_mercado_pago_1_1_client_1_1_preference_1_1_preference_client.html',1,'MercadoPago::Client::Preference']]],
  ['preferenceclient_2ephp_241',['PreferenceClient.php',['../_preference_client_8php.html',1,'']]],
  ['preferenceclientittest_242',['PreferenceClientITTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_integration_1_1_preference_1_1_preference_client_i_t_test.html',1,'MercadoPago::Tests::Client::Integration::Preference']]],
  ['preferenceclientittest_2ephp_243',['PreferenceClientITTest.php',['../_preference_client_i_t_test_8php.html',1,'']]],
  ['preferenceclientunittest_244',['PreferenceClientUnitTest',['../class_mercado_pago_1_1_tests_1_1_client_1_1_unit_1_1_preference_1_1_preference_client_unit_test.html',1,'MercadoPago::Tests::Client::Unit::Preference']]],
  ['preferenceclientunittest_2ephp_245',['PreferenceClientUnitTest.php',['../_preference_client_unit_test_8php.html',1,'']]],
  ['preferencelistresult_246',['PreferenceListResult',['../class_mercado_pago_1_1_resources_1_1_preference_1_1_preference_list_result.html',1,'MercadoPago::Resources::Preference']]],
  ['preferencelistresult_2ephp_247',['PreferenceListResult.php',['../_preference_list_result_8php.html',1,'']]],
  ['preferencesearch_248',['PreferenceSearch',['../class_mercado_pago_1_1_resources_1_1_preference_search.html',1,'MercadoPago::Resources']]],
  ['preferencesearch_2ephp_249',['PreferenceSearch.php',['../_preference_search_8php.html',1,'']]],
  ['preferencias_20del_20usuario_20guardar_5fpreferencia_20php_250',['Preferencias del Usuario (guardar_preferencia.php)',['../endpoints.html#preferencias',1,'']]],
  ['preferencias_2ephp_251',['preferencias.php',['../preferencias_8php.html',1,'']]],
  ['preg_5flast_5ferror_5fmsg_252',['preg_last_error_msg',['../class_symfony_1_1_polyfill_1_1_php80_1_1_php80.html#a883497757b47d2ed8ea2bb1ed51e0cad',1,'Symfony::Polyfill::Php80::Php80']]],
  ['presend_253',['preSend',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a7ddedbf5d2a898f84d8d99c947740d2c',1,'PHPMailer\PHPMailer\PHPMailer\preSend()'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a7ddedbf5d2a898f84d8d99c947740d2c',1,'PHPMailer\PHPMailer\PHPMailer\preSend()']]],
  ['presentacioncuadro_2ephp_254',['presentacioncuadro.php',['../presentacioncuadro_8php.html',1,'']]],
  ['principal_255',['Archivos de negocio y lógica principal',['../index.html#autotoc_md75',1,'']]],
  ['principales_256',['🚀 Funcionalidades Principales',['../index.html#autotoc_md81',1,'']]],
  ['principales_257',['Archivos principales',['../index.html#autotoc_md79',1,'']]],
  ['printchapter_258',['PrintChapter',['../class_p_d_f.html#aaf78159202d63e0e14fc371c89bcf288',1,'PDF\PrintChapter($num, $title, $file)'],['../class_p_d_f.html#aaf78159202d63e0e14fc371c89bcf288',1,'PDF\PrintChapter($num, $title, $file)']]],
  ['privacidad_2ephp_259',['privacidad.php',['../privacidad_8php.html',1,'']]],
  ['pro_260',['🌟 Getting started with payment via Checkout Pro',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md132',1,'']]],
  ['pro_20page_261',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['proceeding_20to_20checkout_20pro_20page_262',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['procesar_5flogin_2ephp_263',['procesar_login.php',['../procesar__login_8php.html',1,'']]],
  ['procesar_5fregistro_2ephp_264',['procesar_registro.php',['../procesar__registro_8php.html',1,'']]],
  ['proceso_265',['Variables utilizadas en el proceso',['../procesar__registro_8php.html#variables',1,'']]],
  ['process_266',['process',['../class_mercado_pago_1_1_client_1_1_order_1_1_order_client.html#aec4e1d3586824ab28156f5ebf18d934a',1,'MercadoPago\Client\Order\OrderClient\process()'],['../class_dotenv_1_1_parser_1_1_lines.html#a621ce29857cb32cea0e7f4af572d9fd6',1,'Dotenv\Parser\Lines\process()']]],
  ['processorder_2ephp_267',['ProcessOrder.php',['../_process_order_8php.html',1,'']]],
  ['production_20or_20sandbox_20access_20token_268',['Step 2: Set production or sandbox access token',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md126',1,'']]],
  ['proyecto_269',['Proyecto',['../index.html#autotoc_md70',1,'🎯 Objetivo del Proyecto'],['../index.html#autotoc_md74',1,'📁 Estructura del Proyecto']]],
  ['proyecto_20n_20i_20c_20o_20l_20e_20versión_20web_270',['Proyecto N.I.C.O.L.E Versión Web',['../index.html',1,'']]],
  ['pull_20request_271',['Pull Request',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md101',1,'']]],
  ['pull_5frequest_5ftemplate_2emd_272',['PULL_REQUEST_TEMPLATE.md',['../_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e_8md.html',1,'']]],
  ['punyencodeaddress_273',['punyencodeAddress',['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a3e8126f823b4c64bdf2b8c614cd22374',1,'PHPMailer\PHPMailer\PHPMailer\punyencodeAddress($address)'],['../class_p_h_p_mailer_1_1_p_h_p_mailer_1_1_p_h_p_mailer.html#a3e8126f823b4c64bdf2b8c614cd22374',1,'PHPMailer\PHPMailer\PHPMailer\punyencodeAddress($address)']]],
  ['put_274',['PUT',['../class_mercado_pago_1_1_net_1_1_http_method.html#af8065fabf58217910a0c910e2f5e7f57',1,'MercadoPago::Net::HttpMethod']]],
  ['putenvadapter_275',['PutenvAdapter',['../class_dotenv_1_1_repository_1_1_adapter_1_1_putenv_adapter.html',1,'Dotenv::Repository::Adapter']]],
  ['putenvadapter_2ephp_276',['PutenvAdapter.php',['../_putenv_adapter_8php.html',1,'']]],
  ['putlink_277',['PutLink',['../class_p_d_f.html#aed7b9ddbd7ec1e334c5687a62129941b',1,'PDF']]]
];
