var searchData=
[
  ['páginas_20informativas_0',['Páginas informativas',['../index.html#autotoc_md56',1,'']]],
  ['pago_1',['Pagos con Mercado Pago',['../index.html#autotoc_md63',1,'']]],
  ['pago_2ephp_2',['pago.php',['../pago_8php.html',1,'']]],
  ['pago_5fexitoso_2ephp_3',['pago_exitoso.php',['../pago__exitoso_8php.html',1,'']]],
  ['pago_5ffallido_2ephp_4',['pago_fallido.php',['../pago__fallido_8php.html',1,'']]],
  ['pago_5fpendiente_2ephp_5',['pago_pendiente.php',['../pago__pendiente_8php.html',1,'']]],
  ['pagos_20con_20mercado_20pago_6',['Pagos con Mercado Pago',['../index.html#autotoc_md63',1,'']]],
  ['php_7',['php',['../endpoints.html#auth',1,'Autenticación (auth.php)'],['../verificar_8php.html#paso2',1,'Capturar datos del formulario login.php'],['../endpoints.html#crud',1,'CRUD Genérico (helpers_crud.php)'],['../endpoints.html#ingredientes',1,'Ingredientes (ingredientes.php)'],['../endpoints.html#recetas',1,'Recetas (recetas.php)'],['../endpoints.html#webhook',1,'Webhook (dashboard/webhook.php)']]],
  ['ping_5fdb_8',['ping_db',['../namespacemain.html#a43ab2d8f0fc7f809b65f51b1cfa4bab2',1,'main']]],
  ['platform_5fcheck_2ephp_9',['platform_check.php',['../platform__check_8php.html',1,'']]],
  ['por_20módulos_10',['Actualmente cuenta con &lt;b&gt;14 endpoints activos&lt;/b&gt; organizados por módulos.',['../endpoints.html#autotoc_md0',1,'']]],
  ['post_11',['POST',['../procesar__registro_8php.html#paso10',1,'Redirección si no es POST'],['../verificar_8php.html#paso7',1,'Redirigir si no es POST'],['../verificar_8php.html#paso1',1,'Verificar método POST']]],
  ['preferencias_2ephp_12',['preferencias.php',['../preferencias_8php.html',1,'']]],
  ['presentacioncuadro_2ephp_13',['presentacioncuadro.php',['../presentacioncuadro_8php.html',1,'']]],
  ['principal_14',['Archivos de negocio y lógica principal',['../index.html#autotoc_md55',1,'']]],
  ['principales_15',['🚀 Funcionalidades Principales',['../index.html#autotoc_md61',1,'']]],
  ['principales_16',['Archivos principales',['../index.html#autotoc_md59',1,'']]],
  ['privacidad_2ephp_17',['privacidad.php',['../privacidad_8php.html',1,'']]],
  ['procesar_5flogin_2ephp_18',['procesar_login.php',['../procesar__login_8php.html',1,'']]],
  ['procesar_5fregistro_2ephp_19',['procesar_registro.php',['../procesar__registro_8php.html',1,'']]],
  ['proceso_20',['Variables utilizadas en el proceso',['../procesar__registro_8php.html#variables',1,'']]],
  ['proyecto_21',['Proyecto',['../index.html#autotoc_md50',1,'🎯 Objetivo del Proyecto'],['../index.html#autotoc_md54',1,'📁 Estructura del Proyecto']]],
  ['proyecto_20n_20i_20c_20o_20l_20e_20versión_20web_22',['Proyecto N.I.C.O.L.E Versión Web',['../index.html',1,'']]]
];
