var searchData=
[
  ['sales_2ephp_0',['Sales.php',['../_sales_8php.html',1,'']]],
  ['scripts_2ephp_1',['scripts.php',['../scripts_8php.html',1,'']]],
  ['security_2emd_2',['SECURITY.md',['../libs_2_p_h_p_mailer_2_s_e_c_u_r_i_t_y_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2_s_e_c_u_r_i_t_y_8md.html',1,'(Espacio de nombres global)']]],
  ['securitycode_2ephp_3',['SecurityCode.php',['../_customer_2_security_code_8php.html',1,'(Espacio de nombres global)'],['../_payment_method_2_security_code_8php.html',1,'(Espacio de nombres global)']]],
  ['sellerreputation_2ephp_4',['SellerReputation.php',['../_seller_reputation_8php.html',1,'']]],
  ['serializer_2ephp_5',['Serializer.php',['../_serializer_8php.html',1,'']]],
  ['serverconstadapter_2ephp_6',['ServerConstAdapter.php',['../_server_const_adapter_8php.html',1,'']]],
  ['settings_2ephp_7',['Settings.php',['../_settings_8php.html',1,'']]],
  ['shipment_2ephp_8',['Shipment.php',['../_shipment_8php.html',1,'']]],
  ['shipments_2ephp_9',['Shipments.php',['../_payment_2_shipments_8php.html',1,'(Espacio de nombres global)'],['../_preference_2_shipments_8php.html',1,'(Espacio de nombres global)']]],
  ['shippingestimateddelivery_2ephp_10',['ShippingEstimatedDelivery.php',['../_shipping_estimated_delivery_8php.html',1,'']]],
  ['shippingoption_2ephp_11',['ShippingOption.php',['../_shipping_option_8php.html',1,'']]],
  ['shippingspeed_2ephp_12',['ShippingSpeed.php',['../_shipping_speed_8php.html',1,'']]],
  ['smtp_2ephp_13',['SMTP.php',['../libs_2_p_h_p_mailer_2src_2_s_m_t_p_8php.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2src_2_s_m_t_p_8php.html',1,'(Espacio de nombres global)']]],
  ['smtputf8_2emd_14',['SMTPUTF8.md',['../libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8_8md.html',1,'(Espacio de nombres global)']]],
  ['some_2ephp_15',['Some.php',['../_some_8php.html',1,'']]],
  ['source_2ephp_16',['Source.php',['../_source_8php.html',1,'']]],
  ['sponsor_2ephp_17',['Sponsor.php',['../_sponsor_8php.html',1,'']]],
  ['status_2ephp_18',['Status.php',['../_status_8php.html',1,'']]],
  ['statusbilling_2ephp_19',['StatusBilling.php',['../_status_billing_8php.html',1,'']]],
  ['statusbuyimmediatepayment_2ephp_20',['StatusBuyImmediatePayment.php',['../_status_buy_immediate_payment_8php.html',1,'']]],
  ['statuslist_2ephp_21',['StatusList.php',['../_status_list_8php.html',1,'']]],
  ['statusshoppingcart_2ephp_22',['StatusShoppingCart.php',['../_status_shopping_cart_8php.html',1,'']]],
  ['storebuilder_2ephp_23',['StoreBuilder.php',['../_store_builder_8php.html',1,'']]],
  ['storedcredential_2ephp_24',['StoredCredential.php',['../_stored_credential_8php.html',1,'']]],
  ['storeinterface_2ephp_25',['StoreInterface.php',['../_store_interface_8php.html',1,'']]],
  ['str_2ephp_26',['Str.php',['../_str_8php.html',1,'']]],
  ['stringable_2ephp_27',['Stringable.php',['../_stringable_8php.html',1,'']]],
  ['stringstore_2ephp_28',['StringStore.php',['../_string_store_8php.html',1,'']]],
  ['stylesheet_2ephp_29',['stylesheet.php',['../stylesheet_8php.html',1,'']]],
  ['submerchant_2ephp_30',['SubMerchant.php',['../_sub_merchant_8php.html',1,'']]],
  ['subscriptiondata_2ephp_31',['SubscriptionData.php',['../_subscription_data_8php.html',1,'']]],
  ['subscriptionsequence_2ephp_32',['SubscriptionSequence.php',['../_subscription_sequence_8php.html',1,'']]],
  ['success_2ephp_33',['Success.php',['../_success_8php.html',1,'']]],
  ['summarized_2ephp_34',['Summarized.php',['../_summarized_8php.html',1,'']]],
  ['symbol_2ephp_35',['symbol.php',['../symbol_8php.html',1,'']]]
];
