var searchData=
[
  ['dashboard_20webhook_20php_0',['Webhook de MercadoPago (dashboard/webhook.php)',['../endpoints.html#webhook',1,'']]],
  ['datos_1',['Consultar usuario en la base de datos',['../procesar__registro_8php.html#paso4',1,'']]],
  ['datos_20del_20formulario_20login_20php_2',['Capturar datos del formulario login.php',['../procesar__registro_8php.html#paso2',1,'']]],
  ['de_20éxito_3',['Redirección en caso de éxito',['../procesar__registro_8php.html#pasoFinal',1,'']]],
  ['de_20datos_4',['Consultar usuario en la base de datos',['../procesar__registro_8php.html#paso4',1,'']]],
  ['de_20errores_5',['de errores',['../procesar__registro_8php.html#paso9',1,'Manejo de errores'],['../C:/Users/alex/Downloads/web2/htdocs/dashboard/registro.php#manejo_errores',1,'Manejo de errores']]],
  ['de_20flujo_6',['Resumen de flujo',['../C:/Users/alex/Downloads/web2/htdocs/dashboard/verificar.php#resumen',1,'']]],
  ['de_20la_20interfaz_7',['Dinámica de la interfaz',['../C:/Users/alex/Downloads/web2/htdocs/dashboard/registro.php#interfaz',1,'']]],
  ['de_20mensajería_20con_20ia_8',['Módulo de mensajería con IA',['../index.html#autotoc_md77',1,'']]],
  ['de_20mercadopago_20dashboard_20webhook_20php_9',['Webhook de MercadoPago (dashboard/webhook.php)',['../endpoints.html#webhook',1,'']]],
  ['de_20negocio_20y_20lógica_20principal_10',['Archivos de negocio y lógica principal',['../index.html#autotoc_md75',1,'']]],
  ['de_20obsoletos_11',['Lista de obsoletos',['../deprecated.html',1,'']]],
  ['de_20seguridad_12',['Consideraciones de seguridad',['../dashboard_2login_8php.html#seguridad',1,'']]],
  ['de_20sesión_20login_20php_13',['Inicio de Sesión (login.php)',['../endpoints.html#login',1,'']]],
  ['de_20sesiones_20y_20roles_14',['Gestión de Sesiones y Roles',['../index.html#autotoc_md84',1,'']]],
  ['de_20usuario_20register_20php_15',['Registro de Usuario (register.php)',['../endpoints.html#registro',1,'']]],
  ['de_20usuarios_16',['Autenticación de Usuarios',['../index.html#autotoc_md82',1,'']]],
  ['de_20verificación_20reenviar_5fcodigo_20php_17',['Reenviar Código de Verificación (reenviar_codigo.php)',['../endpoints.html#reenviar',1,'']]],
  ['del_20formulario_18',['Campos del formulario',['../C:/Users/alex/Downloads/web2/htdocs/dashboard/registro.php#campos',1,'']]],
  ['del_20formulario_20login_20php_19',['Capturar datos del formulario login.php',['../procesar__registro_8php.html#paso2',1,'']]],
  ['del_20proyecto_20',['del Proyecto',['../index.html#autotoc_md70',1,'🎯 Objetivo del Proyecto'],['../index.html#autotoc_md74',1,'📁 Estructura del Proyecto']]],
  ['del_20usuario_20guardar_5fpreferencia_20php_21',['Preferencias del Usuario (guardar_preferencia.php)',['../endpoints.html#preferencias',1,'']]],
  ['dependencias_22',['Dependencias',['../procesar__registro_8php.html#dependencias',1,'']]],
  ['dependency_20update_23',['Dependency Update',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md107',1,'']]],
  ['desarrollador_24',['👥 Equipo Desarrollador',['../index.html#autotoc_md89',1,'']]],
  ['dinámica_20de_20la_20interfaz_25',['Dinámica de la interfaz',['../C:/Users/alex/Downloads/web2/htdocs/dashboard/registro.php#interfaz',1,'']]],
  ['docs_26',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['documentación_20y_20utilidades_27',['Documentación y utilidades',['../index.html#autotoc_md78',1,'']]],
  ['documentation_28',['Documentation',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md137',1,'📚 Documentation'],['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md53',1,'Documentation'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md152',1,'Documentation'],['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md114',1,'Step 5: Review the Documentation']]],
  ['documento_20visual_20y_20técnico_29',['Endpoints N.I.C.O.L.E — Documento visual y técnico',['../endpoints.html',1,'']]]
];
