var searchData=
[
  ['código_20de_20verificación_20reenviar_5fcodigo_20php_0',['Reenviar Código de Verificación (reenviar_codigo.php)',['../endpoints.html#reenviar',1,'']]],
  ['código_20verificar_20php_1',['Verificar Código (verificar.php)',['../endpoints.html#verificar',1,'']]],
  ['c_20o_20l_20e_20—_20documento_20visual_20y_20técnico_2',['Endpoints N.I.C.O.L.E — Documento visual y técnico',['../endpoints.html',1,'']]],
  ['c_20o_20l_20e_20versión_20web_3',['Proyecto N.I.C.O.L.E Versión Web',['../index.html',1,'']]],
  ['campos_20del_20formulario_4',['Campos del formulario',['../C:/Users/alex/Downloads/web2/htdocs/dashboard/registro.php#campos',1,'']]],
  ['capturar_20datos_20del_20formulario_20login_20php_5',['Capturar datos del formulario login.php',['../procesar__registro_8php.html#paso2',1,'']]],
  ['caso_20de_20éxito_6',['Redirección en caso de éxito',['../procesar__registro_8php.html#pasoFinal',1,'']]],
  ['cerrar_20conexión_7',['Cerrar conexión',['../procesar__registro_8php.html#paso8',1,'']]],
  ['change_20feature_20request_8',['Request For Change / Feature Request',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md99',1,'']]],
  ['changed_20since_20moving_20from_20sourceforge_9',['changed since moving from SourceForge',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md61',1,'What's changed since moving from SourceForge?'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md160',1,'What's changed since moving from SourceForge?']]],
  ['changelog_10',['Changelog',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md59',1,'Changelog'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md158',1,'Changelog']]],
  ['changes_11',['Major Changes',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md105',1,'']]],
  ['changes_12',['General changes',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html#autotoc_md117',1,'']]],
  ['changes_20made_20to_20the_20feature_3a_13',['Changes made to the feature:',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html',1,'']]],
  ['checklist_3a_14',['PR validation checklist:',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html#autotoc_md119',1,'']]],
  ['checkout_20pro_15',['🌟 Getting started with payment via Checkout Pro',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md132',1,'']]],
  ['checkout_20pro_20page_16',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['class_20for_20php_17',['class for PHP',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md43',1,'PHPMailer – A full-featured email creation and transfer class for PHP'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md142',1,'PHPMailer – A full-featured email creation and transfer class for PHP']]],
  ['client_18',['Step 3: Initialize the API client',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md127',1,'']]],
  ['closed_19',['Issues closed',['../md_vendor_2mercadopago_2dx-php_2_p_u_l_l___r_e_q_u_e_s_t___t_e_m_p_l_a_t_e.html#autotoc_md118',1,'']]],
  ['code_20guidelines_20',['Code Guidelines',['../md_vendor_2mercadopago_2dx-php_2_c_o_d_i_n_g___g_u_i_d_e_l_i_n_e_s.html#autotoc_md92',1,'']]],
  ['coding_20guidance_21',['Coding Guidance',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md98',1,'']]],
  ['coding_20guidelines_22',['Coding Guidelines',['../md_vendor_2mercadopago_2dx-php_2_c_o_d_i_n_g___g_u_i_d_e_l_i_n_e_s.html',1,'']]],
  ['comment_20guidelines_23',['Comment Guidelines',['../md_vendor_2mercadopago_2dx-php_2_c_o_d_i_n_g___g_u_i_d_e_l_i_n_e_s.html#autotoc_md93',1,'']]],
  ['composer_24',['Use of Composer',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md108',1,'']]],
  ['composer_20vendor_20folder_25',['Step 1: Require the library from your Composer vendor folder',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md125',1,'']]],
  ['con_20ia_26',['con IA',['../index.html#autotoc_md77',1,'Módulo de mensajería con IA'],['../index.html#autotoc_md85',1,'Mensajería con IA']]],
  ['con_20mercado_20pago_27',['Pagos con Mercado Pago',['../index.html#autotoc_md83',1,'']]],
  ['conclusion_28',['Conclusion',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md115',1,'']]],
  ['conexión_29',['Cerrar conexión',['../procesar__registro_8php.html#paso8',1,'']]],
  ['consideraciones_20de_20seguridad_30',['Consideraciones de seguridad',['../dashboard_2login_8php.html#seguridad',1,'']]],
  ['consultar_20usuario_20en_20la_20base_20de_20datos_31',['Consultar usuario en la base de datos',['../procesar__registro_8php.html#paso4',1,'']]],
  ['contenido_20informativo_32',['Contenido informativo',['../index.html#autotoc_md86',1,'']]],
  ['contraseña_20y_20guardar_20sesión_33',['Verificar contraseña y guardar sesión',['../procesar__registro_8php.html#paso5',1,'']]],
  ['contribute_34',['How to contribute',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md97',1,'']]],
  ['contributing_35',['Contributing',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md138',1,'🤝 Contributing'],['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md56',1,'Contributing'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md155',1,'Contributing']]],
  ['contributing_20to_20the_20mercado_20pago_20php_20sdk_36',['Contributing to the Mercado Pago PHP SDK',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['correo_37',['Validar correo',['../procesar__registro_8php.html#paso3',1,'']]],
  ['create_20an_20authentication_20function_38',['Step 2: Create an authentication function',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md134',1,'']]],
  ['create_20customer_20s_20preference_20before_20proceeding_20to_20checkout_20pro_20page_39',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['create_20the_20preference_20on_20mercado_20pago_20docs_40',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['create_20the_20request_20array_41',['Step 4: Create the request array',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md128',1,'']]],
  ['create_20the_20request_20options_20setting_20x_20idempotency_20key_42',['Step 5: Create the request options, setting X-Idempotency-Key',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md129',1,'']]],
  ['creation_20and_20transfer_20class_20for_20php_43',['creation and transfer class for PHP',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md43',1,'PHPMailer – A full-featured email creation and transfer class for PHP'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md142',1,'PHPMailer – A full-featured email creation and transfer class for PHP']]],
  ['customer_20s_20preference_20before_20proceeding_20to_20checkout_20pro_20page_44',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]]
];
