var searchData=
[
  ['s_20changed_20since_20moving_20from_20sourceforge_0',['s changed since moving from SourceForge',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md61',1,'What's changed since moving from SourceForge?'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md160',1,'What's changed since moving from SourceForge?']]],
  ['s_20preference_20before_20proceeding_20to_20checkout_20pro_20page_1',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['sandbox_20access_20token_2',['Step 2: Set production or sandbox access token',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md126',1,'']]],
  ['scripts_20js_3',['Inteligencia Artificial (scripts.js)',['../endpoints.html#ia',1,'']]],
  ['sdk_4',['Contributing to the Mercado Pago PHP SDK',['../md_vendor_2mercadopago_2dx-php_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['sdk_20for_20php_5',['Mercado Pago SDK for PHP',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md120',1,'']]],
  ['sdk_20installation_6',['Step 1: SDK Installation',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md110',1,'']]],
  ['sdk_20structure_7',['SDK Structure',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md106',1,'']]],
  ['sdk_20v2_20to_20v3_8',['Migration Guide from MercadoPago PHP SDK v2 to v3',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['security_9',['Security',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md55',1,'Security'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md154',1,'Security']]],
  ['security_20notices_20relating_20to_20phpmailer_10',['Security notices relating to PHPMailer',['../md_libs_2_p_h_p_mailer_2_s_e_c_u_r_i_t_y.html',1,'Security notices relating to PHPMailer'],['../md_vendor_2phpmailer_2phpmailer_2_s_e_c_u_r_i_t_y.html',1,'Security notices relating to PHPMailer']]],
  ['seguridad_11',['Consideraciones de seguridad',['../dashboard_2login_8php.html#seguridad',1,'']]],
  ['sesión_12',['Verificar contraseña y guardar sesión',['../procesar__registro_8php.html#paso5',1,'']]],
  ['sesión_20login_20php_13',['Inicio de Sesión (login.php)',['../endpoints.html#login',1,'']]],
  ['sesiones_20y_20roles_14',['Gestión de Sesiones y Roles',['../index.html#autotoc_md84',1,'']]],
  ['set_20production_20or_20sandbox_20access_20token_15',['Step 2: Set production or sandbox access token',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md126',1,'']]],
  ['setting_20x_20idempotency_20key_16',['Step 5: Create the request options, setting X-Idempotency-Key',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md129',1,'']]],
  ['short_20history_20of_20utf_208_20in_20email_17',['short history of UTF 8 in email',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html',1,'A short history of UTF-8 in email']]],
  ['si_20hay_20errores_18',['Redirigir si hay errores',['../procesar__registro_8php.html#paso6',1,'']]],
  ['si_20no_20es_20post_19',['si no es POST',['../procesar__registro_8php.html#paso10',1,'Redirección si no es POST'],['../procesar__registro_8php.html#paso7',1,'Redirigir si no es POST']]],
  ['simple_20example_20',['Simple Example',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md51',1,'A Simple Example'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md150',1,'A Simple Example']]],
  ['since_20moving_20from_20sourceforge_21',['since moving from SourceForge',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md61',1,'What's changed since moving from SourceForge?'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md160',1,'What's changed since moving from SourceForge?']]],
  ['smtputf8_22',['SMTPUTF8',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html#autotoc_md65',1,'SMTPUTF8'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html#autotoc_md164',1,'SMTPUTF8']]],
  ['smtputf8_20in_20phpmailer_23',['SMTPUTF8 in PHPMailer',['../md_libs_2_p_h_p_mailer_2_s_m_t_p_u_t_f8.html#autotoc_md66',1,'SMTPUTF8 in PHPMailer'],['../md_vendor_2phpmailer_2phpmailer_2_s_m_t_p_u_t_f8.html#autotoc_md165',1,'SMTPUTF8 in PHPMailer']]],
  ['sourceforge_24',['SourceForge',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md61',1,'What's changed since moving from SourceForge?'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md160',1,'What's changed since moving from SourceForge?']]],
  ['sponsorship_25',['Sponsorship',['../C:/Users/alex/Downloads/web2/htdocs/libs/PHPMailer/README.md#autotoc_md57',1,'Sponsorship'],['../C:/Users/alex/Downloads/web2/htdocs/vendor/phpmailer/phpmailer/README.md#autotoc_md156',1,'Sponsorship']]],
  ['started_20with_20payment_20via_20checkout_20pro_26',['🌟 Getting started with payment via Checkout Pro',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md132',1,'']]],
  ['started_20with_20payment_20via_20your_20own_20website_20forms_27',['🌟 Getting Started with payment via your own website forms',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md124',1,'']]],
  ['step_201_3a_20require_20the_20libraries_28',['Step 1: Require the libraries',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md133',1,'']]],
  ['step_201_3a_20require_20the_20library_20from_20your_20composer_20vendor_20folder_29',['Step 1: Require the library from your Composer vendor folder',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md125',1,'']]],
  ['step_201_3a_20sdk_20installation_30',['Step 1: SDK Installation',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md110',1,'']]],
  ['step_202_3a_20create_20an_20authentication_20function_31',['Step 2: Create an authentication function',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md134',1,'']]],
  ['step_202_3a_20set_20production_20or_20sandbox_20access_20token_32',['Step 2: Set production or sandbox access token',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md126',1,'']]],
  ['step_202_3a_20update_20imports_33',['Step 2: Update Imports',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md111',1,'']]],
  ['step_203_3a_20create_20customer_20s_20preference_20before_20proceeding_20to_20checkout_20pro_20page_34',['Step 3: Create customer&apos;s preference before proceeding to Checkout Pro page',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md135',1,'']]],
  ['step_203_3a_20initialize_20the_20api_20client_35',['Step 3: Initialize the API client',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md127',1,'']]],
  ['step_203_3a_20update_20methods_36',['Step 3: Update Methods',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md112',1,'']]],
  ['step_204_3a_20create_20the_20preference_20on_20mercado_20pago_20docs_37',['Step 4: Create the preference on Mercado Pago (&lt;a href=&quot;https://www.mercadopago.com.br/developers/pt/docs/sdks-library/server-side/php/preferences&quot;&gt;DOCS&lt;/a&gt;)',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md136',1,'']]],
  ['step_204_3a_20create_20the_20request_20array_38',['Step 4: Create the request array',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md128',1,'']]],
  ['step_204_3a_20update_20exception_20handling_39',['Step 4: Update exception handling',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md113',1,'']]],
  ['step_205_3a_20create_20the_20request_20options_20setting_20x_20idempotency_20key_40',['Step 5: Create the request options, setting X-Idempotency-Key',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md129',1,'']]],
  ['step_205_3a_20review_20the_20documentation_41',['Step 5: Review the Documentation',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md114',1,'']]],
  ['step_206_3a_20make_20the_20request_42',['Step 6: Make the request',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md130',1,'']]],
  ['step_207_3a_20handle_20exceptions_43',['Step 7: Handle exceptions',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md131',1,'']]],
  ['step_20by_20step_20migration_44',['Step-by-Step Migration',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md109',1,'']]],
  ['step_20migration_45',['Step-by-Step Migration',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md109',1,'']]],
  ['structure_46',['SDK Structure',['../md_vendor_2mercadopago_2dx-php_2_m_i_g_r_a_t_i_o_n___g_u_i_d_e.html#autotoc_md106',1,'']]],
  ['support_47',['❤️ Support',['../C:/Users/alex/Downloads/web2/htdocs/vendor/mercadopago/dx-php/README.md#autotoc_md140',1,'']]]
];
